APIGOV-22429 Create Manage product plans page
Axway/amplify-central pull request #121
Opened 2022-04-22 22:20 UTC by lbadenhop

Thank you for your contribution to the Amplify-Central repo.

## Describe the changes

Enter a brief description of your changes here to communicate to the maintainers what you changed and why.

## Checklist for contributors

Before submitting this PR, please make sure:

* [ ] You have read the [contribution guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/)
* [ ] You have signed the [Axway CLA](https://cla.axway.com/)
* [ ] You have verified the technical accuracy of your change
* [ ] You have verified that your change does not expose any sensitive information (passwords, keys, etc.)
* [ ] You have followed the [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)  (unless this is is a Netlify CMS contribution)

_Put an x in the boxes that apply. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your change._

2022-04-22 22:31 UTC, lbadenhop commented
@georgiana-caras Please review and let me know when this functionality will be released (at which time this PR will be merged and the "Functionality coming soon" note in the Product management page will be deleted). Also, this page overlaps some of the content in https://docs.axway.com/bundle/amplify-central/page/docs/manage_product_foundry/foundry_product_management/index.html.

2022-05-05 22:07 UTC, georgiana-caras requested changes

2022-05-05 22:07 UTC, georgiana-caras commented on content/en/docs/manage_product_foundry/manage_product_plans.md
> +**Quotas** - describes the itemized units per resource or group of resources in product, and how much of those units they are entitled to use over a period.
billing period

2022-05-05 22:07 UTC, georgiana-caras commented on content/en/docs/manage_product_foundry/manage_product_plans.md
> +| Archived   | All associated subscriptions to this plan will be expired and the plan will be removed from the Marketplace.  |
Archived: After a plan is deprecated with an auto-expiration date, the plan will be automatically to archived the movement the last subscription moves to expired.

2022-05-05 22:07 UTC, georgiana-caras commented on content/en/docs/manage_product_foundry/manage_product_plans.md
> +| Deprecated | Indicates that the plan is listed in the marketplace, but new subscriptions are not allowed. Plan is not visible on the plan page.
Deprecated: Indicates that new subscriptions on this plan are not allowed. Consumers with an existing subscription can continue to stay on this plan until their subscription expires.

2022-05-06 22:21 UTC, lbadenhop commented
@georgiana-caras Your changes have been added. Please review.

2022-05-09 16:17 UTC, merged

2022-05-09 22:04 UTC, cbordier reviewed
I approve the changes