Update page in Manage your Asset Catalog section “tags_attributes_categories”
Axway/amplify-central pull request #127
Opened 2022-04-28 16:32 UTC by robertengaxway

Automatically generated by Netlify CMS

2022-04-29 20:53 UTC, lbadenhop commented
@robertengaxway I fixed the markdown error and reviewed/edited the content. Is this topic complete? Are you going to document "How to" apply tags, attributes and categories

2022-05-05 18:39 UTC, cbordier approved these changes
Looks good to me

2022-05-05 21:57 UTC, georgiana-caras requested changes

2022-05-05 21:57 UTC, georgiana-caras commented on content/en/docs/manage_asset_catalog/tags_attributes_categories.md
> +Tags are keywords that can assigned to catalog assets and used to search for assets. You can create tags with any special characters. For example, `_ - & () \ []` and all types of special language ch
be assigned

2022-05-05 21:57 UTC, georgiana-caras commented on content/en/docs/manage_asset_catalog/tags_attributes_categories.md
> +2. Either select a asset version in the Draft state or click either **Create Draft** or **Edit Asset** on the right-side details.
an asset

2022-05-05 21:57 UTC, georgiana-caras commented on content/en/docs/manage_asset_catalog/tags_attributes_categories.md
> +Searching through an unordered list of assets can become a dauting tasks and make assets less organized. Central Admin and Product Manager users can create categories to group assets in the Amplify A
remove product manager as they cannot create

2022-05-05 21:57 UTC, georgiana-caras commented on content/en/docs/manage_asset_catalog/tags_attributes_categories.md
> +Only users that are assigned the **Central Admin** or **Product Manager** role can create, edit and delete categories. Categories are created at the Organization level and available to all teams to a
catalog manager cannot create categories, please remove

2022-05-05 22:45 UTC, robertengaxway commented on content/en/docs/manage_asset_catalog/tags_attributes_categories.md
> +2. Either select a asset version in the Draft state or click either **Create Draft** or **Edit Asset** on the right-side details.
> an asset

edited

2022-05-05 22:47 UTC, robertengaxway reviewed
I updated the changes suggested by Georgi

2022-05-06 15:57 UTC, georgiana-caras approved these changes

2022-05-06 22:02 UTC, lbadenhop approved these changes

2022-05-09 14:23 UTC, merged