apigov-23206 - Adding the team exclusion
Axway/amplify-central pull request #177
Opened 2022-08-11 18:16 UTC by cbordier

Thank you for your contribution to the Amplify-Central repo.

## Describe the changes

Enter a brief description of your changes here to communicate to the maintainers what you changed and why.

## Checklist for contributors

Before submitting this PR, please make sure:

* [X] You have read the [contribution guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/)
* [X] You have signed the [Axway CLA](https://cla.axway.com/)
* [X] You have verified the technical accuracy of your change
* [X] You have verified that your change does not expose any sensitive information (passwords, keys, etc.)
* [X] You have followed the [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)  (unless this is is a Netlify CMS contribution)

_Put an x in the boxes that apply. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your change._

2022-08-11 18:22 UTC, cbordier commented
@lbadenhop ready for review.

2022-08-12 19:08 UTC, lbadenhop commented on content/en/docs/manage_marketplace/set_product_visibility.md
>  2. Select **Products > All Products**. The product list view is displayed.
```suggestion
2. Select **All Products**. The product list view is displayed.
```

2022-08-12 19:15 UTC, lbadenhop commented on content/en/docs/manage_marketplace/set_product_visibility.md
>      * **Everyone** - (default) make the product visible to all registered users in your provider organization.
```suggestion
    * **Everyone** - (default) all registered users in your provider organization can see the product in the Marketplace
```

2022-08-12 19:16 UTC, lbadenhop commented on content/en/docs/manage_marketplace/set_product_visibility.md
> +    * **Exclude selected teams** - only members not part of selected teams can see the product in Marketplace
```suggestion
    * **Exclude selected teams** - only members that are not part of selected teams can see the product in the Marketplace
```

2022-08-12 19:18 UTC, lbadenhop commented on content/en/docs/manage_marketplace/set_product_visibility.md
> +    * **None** - nobody on arketpalce will be able to see the product
```suggestion
    * **None** - the product is not visible to anyone in the Marketplace
```

2022-08-12 19:24 UTC, lbadenhop requested changes
@cbordier Please see my comments. If you agree with the changes, adjust the visibility settings under "Make product available to Marketplace users.

2022-08-12 20:08 UTC, lbadenhop approved these changes

2022-08-12 20:23 UTC, merged