August Release Notes
Axway/amplify-central pull request #185
Opened 2022-08-19 14:29 UTC by lbadenhop

Thank you for your contribution to the Amplify-Central repo.

## Changes

New format. Archived previous Release Notes.

## Checklist for contributors

Before submitting this PR, please make sure:

* [ ] You have read the [contribution guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/)
* [ ] You have signed the [Axway CLA](https://cla.axway.com/)
* [ ] You have verified the technical accuracy of your change
* [ ] You have verified that your change does not expose any sensitive information (passwords, keys, etc.)
* [ ] You have followed the [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)  (unless this is is a Netlify CMS contribution)

_Put an x in the boxes that apply. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your change._

2022-08-19 17:10 UTC, lbadenhop commented
@cbordier @robertengaxway Ready for content. I'll add Georgi as a reviewer once the content is updated.

2022-08-19 21:08 UTC, lbadenhop commented
@cbordier @robertengaxway Two formatting caveats: 
* Colons (:) cannot be used in topic titles, as suggested by Georgi (Marketplace: August 26th 2022). It is now Marketplace August 26th 2022
* Cannot duplicate Heading in the same page, as suggested by Georgi (Feature updates, Security updates, etc.). The headings now include the the component name. For example, Feature updates for Service Registry.

2022-08-29 15:42 UTC, georgiana-caras requested changes

2022-08-29 15:42 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20220826_marketplace.md
> +This will allow providers to always make the product discoverable without having to adjust the product visibility settings as they onboard new teams.
Setting the product visibility based on tags is currently available via the APIs  / CLI.

2022-08-29 15:42 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20220826_marketplace.md
> +Categories can be flagged to show as featured on the Marketpalce Homepage. A maximum of 5 categories can set as Featured. This will enable Catalog Managers to highlight and advertise a group of produ
Is this statement still valid, as featured categories cannot be set from the UI? I recommend to specify that featured categories can be set using the APIs / CLI.

2022-08-29 16:45 UTC, cbordier commented on content/en/docs/amplify_relnotes/20220826_marketplace.md
> +Categories can be flagged to show as featured on the Marketpalce Homepage. A maximum of 5 categories can set as Featured. This will enable Catalog Managers to highlight and advertise a group of produ
Yes it can be done from UI - no need to change the sentence

2022-08-29 16:46 UTC, cbordier commented on content/en/docs/amplify_relnotes/20220826_marketplace.md
> +This will allow providers to always make the product discoverable without having to adjust the product visibility settings as they onboard new teams.
It should be deployed today so we can keep it.

2022-08-29 20:28 UTC, georgiana-caras approved these changes

2022-08-29 23:09 UTC, merged