September 9th Release Notes
Axway/amplify-central pull request #191
Opened 2022-09-01 22:22 UTC by lbadenhop

Thank you for your contribution to the Amplify-Central repo.

## Changes

Release Notes for September 9th.

## Checklist for contributors

Before submitting this PR, please make sure:

* [ ] You have read the [contribution guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/)
* [ ] You have signed the [Axway CLA](https://cla.axway.com/)
* [ ] You have verified the technical accuracy of your change
* [ ] You have verified that your change does not expose any sensitive information (passwords, keys, etc.)
* [ ] You have followed the [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)  (unless this is is a Netlify CMS contribution)

_Put an x in the boxes that apply. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your change._

2022-09-07 16:48 UTC, georgiana-caras requested changes

2022-09-07 16:48 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20220909_marketplace.md
> +* **Assigning category to product removes many product details** - Previously when creating a category and assigning product(s) to it, the assigned product(s) changed to Draft status. Now, the catego
**Assigning category to product removes many product details** to be replaced with: **Assigning a product to a category changed the product state** - Previously when creating a category from the category management screen, and assigning product (s) to it, the assigned product (s) changed to Draft status. Now, the category assignment does not create a product Draft release.

2022-09-07 16:48 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20220909_marketplace.md
> +* **Marketplace home page - filter per featured category** - The featured categories displayed in the home page allows the user to see all related product when using the "View products" link on a cat
Replace *Marketplace home page - filter per featured category** with **View products in a featured category** - Consumers can now see the products included in the featured categories displayed on the home page, by clicking on the "View products" link shown for each category.

2022-09-07 16:48 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20220909_marketplace.md
> +* **Markeplace browse product - filter per category** - the browse home page is enriched with the category filter and allow user to see all product for a selected category. A breadcrumb is added as s
Replace **Markeplace browse product - filter per category**  with **Filter products by categories** - the browse products page has been enhanced with a category filter to allow users to filter the catalog of products by categories.  A breadcrumb is added to the result page once the filter in applied to enable users to unselect a selected category and reset the filter.

2022-09-07 16:48 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20220909_marketplace.md
> +* **Paid plan base price with large number crash the backend** - Previously when using a big number in paid plan, the backend api return a 500 error. Now, the UI does not allow to enter a number havi
crashed

2022-09-08 20:20 UTC, lbadenhop commented on content/en/docs/amplify_relnotes/20220909_marketplace.md
> +* **Category management** - Categories can now be edited, deleted and previewed from a dedicated screen at **Product Foundry > Categories**.
updated

2022-09-12 18:40 UTC, achoudhary-axway commented
@lbadenhop  and @sallylanda6 - I took a look on the preview but don't see anything mentioned for Business Insights / Subscriptions.

2022-09-12 18:42 UTC, achoudhary-axway commented
@lbadenhop  and @sallylanda6 - I took a look but don't see any content for Business Insights / Subscription.

![image](https://user-images.githubusercontent.com/99050449/189731222-d8ded830-8e17-4260-b665-08a27df8a9e3.png)

2022-09-12 19:51 UTC, achoudhary-axway commented on content/en/docs/amplify_relnotes/20220909_marketplace.md
> +There are no enhancements and bug fixes in this release.
Subscriptions - API Providers can now see the usage and quota compliance of Subscriptions to their APIs by different Consuming Teams.

2022-09-12 22:28 UTC, robertengaxway approved these changes

2022-09-12 23:18 UTC, georgiana-caras approved these changes

2022-09-13 00:57 UTC, merged