APIGOV-23251 - Product category management
Axway/amplify-central pull request #193
Opened 2022-09-08 20:16 UTC by cbordier

Thank you for your contribution to the Amplify-Central repo.

## Describe the changes

Update existing category management page to introduce the new features.

## Checklist for contributors

Before submitting this PR, please make sure:

* [X] You have read the [contribution guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/)
* [X] You have signed the [Axway CLA](https://cla.axway.com/)
* [X] You have verified the technical accuracy of your change
* [X] You have verified that your change does not expose any sensitive information (passwords, keys, etc.)
* [X] You have followed the [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)  (unless this is is a Netlify CMS contribution)

_Put an x in the boxes that apply. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your change._

2022-09-09 15:08 UTC, georgiana-caras requested changes
Correct some typos and make small adjustments to the content.

2022-09-09 15:08 UTC, georgiana-caras commented on content/en/docs/manage_product_foundry/foundry_product_tags_attributes_categories.md
> +* **global**: these are legacy category that have been created using the Unified Catalog category management system or when creating category when creating a product. They can be used either with Ass
categories

2022-09-09 15:08 UTC, georgiana-caras commented on content/en/docs/manage_product_foundry/foundry_product_tags_attributes_categories.md
> +* **product specific**:  these category can only be assigned to a product.
categories

2022-09-09 15:08 UTC, georgiana-caras commented on content/en/docs/manage_product_foundry/foundry_product_tags_attributes_categories.md
> +* private: the category is used for filtering the product foundry catalog only
Product Foundry instead of product foundry

2022-09-09 15:08 UTC, georgiana-caras commented on content/en/docs/manage_product_foundry/foundry_product_tags_attributes_categories.md
> +* public: the category is used to filter the product foundry catalog as well as the marketplace product.
Product Foundry

2022-09-09 15:08 UTC, georgiana-caras commented on content/en/docs/manage_product_foundry/foundry_product_tags_attributes_categories.md
> +A public category can be set as **Featured** category to enable the provider to highlight and advertise this category and the associated products from the marketplace home page. In that case, the cat
A public category can be set as **Featured** by providers to highlight and advertise this category and the associated products on the Marketplace Home Page.

2022-09-09 15:08 UTC, georgiana-caras commented on content/en/docs/manage_product_foundry/foundry_product_tags_attributes_categories.md
> +2. Naviagte to the **Catalog > Product Foundry > Categories**
typo Naviagte; to be corrected to Navigate

2022-09-09 15:08 UTC, georgiana-caras commented on content/en/docs/manage_product_foundry/foundry_product_tags_attributes_categories.md
>  If the product is already published to a marketplace, the change of category will be reflected almost immediately in the marketplace.
remove almost

2022-09-09 15:08 UTC, georgiana-caras commented on content/en/docs/manage_product_foundry/foundry_product_tags_attributes_categories.md
> +Using the Axway central CLI, it is possible to edit any category. A global category can be converted to a product category if it was only assigned to product. For that the following should be added t
Move the  CLI section after describing the steps to update a category from the UI.

2022-09-09 15:08 UTC, georgiana-caras commented on content/en/docs/manage_product_foundry/foundry_product_tags_attributes_categories.md
> +2. Naviagte to the **Catalog > Product Foundry > Categories**
typo Naviagte; to be corrected to Navigate

2022-09-09 15:08 UTC, georgiana-caras commented on content/en/docs/manage_product_foundry/foundry_product_tags_attributes_categories.md
> +2. Naviagte to the **Catalog > Product Foundry > Categories**
typo Naviagte; to be corrected to Navigate

2022-09-09 15:08 UTC, georgiana-caras commented on content/en/docs/manage_product_foundry/foundry_product_tags_attributes_categories.md
> +2. Naviagte to the **Catalog > Product Foundry > Categories**
typo Naviagte; to be corrected to Navigate

2022-09-09 15:08 UTC, georgiana-caras commented on content/en/docs/manage_product_foundry/foundry_product_tags_attributes_categories.md
> +4. Clicking the Category name will open the category preview side blade where user is allowed to change the category visibility as well as the Fetured category toggle. If five Featured category are a
If five Featured category -> If five Featured categories

2022-09-09 15:08 UTC, georgiana-caras commented on content/en/docs/manage_product_foundry/foundry_product_tags_attributes_categories.md
> +2. click on the Categories field in the details side panel and select the category from the list. The list contains the global categories and the product specific category. To remove a Category, clic
click -> Click

2022-09-09 15:08 UTC, georgiana-caras commented on content/en/docs/manage_product_foundry/foundry_product_tags_attributes_categories.md
> +Catalog manager users can only assigned existing category.
assigned -> assign

2022-09-12 18:18 UTC, lbadenhop commented
@cbordier Please review my edits and confirm that all of Georgiana's edit were incorporated.

2022-09-12 18:51 UTC, cbordier commented
@lbadenhop, your edits looks good.
@georgiana-caras can you approve the changes?

2022-09-12 20:06 UTC, lbadenhop approved these changes

2022-09-12 20:30 UTC, georgiana-caras approved these changes

2022-09-12 21:02 UTC, merged