Consumer org management
Axway/amplify-central pull request #210
Opened 2022-10-15 00:14 UTC by cbordier

Thank you for your contribution to the Amplify-Central repo.

## Describe the changes

Adding information about the consumer org management

## Checklist for contributors

Before submitting this PR, please make sure:

* [X] You have read the [contribution guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/)
* [X] You have signed the [Axway CLA](https://cla.axway.com/)
* [X] You have verified the technical accuracy of your change
* [X] You have verified that your change does not expose any sensitive information (passwords, keys, etc.)
* [X] You have followed the [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)  (unless this is is a Netlify CMS contribution)

_Put an x in the boxes that apply. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your change._

2022-10-17 21:55 UTC, georgiana-caras requested changes
please make the highlighted changes before publishing the documentation (Contains rephrasing of content, correction of typos)

2022-10-17 21:55 UTC, georgiana-caras commented on content/en/docs/manage_marketplace/consumer_experience/_index.md
>  A *Private marketplace* can be browsed by navigating to the configured Marketplace URL, for example: `http://acme.marketplace.axway.com`. Consumers are redirected to a login screen and ask to enter t
'asked'

2022-10-17 21:55 UTC, georgiana-caras commented on content/en/docs/manage_marketplace/consumer_experience/_index.md
> +There are two ways of getting credentials for a marketplace:
There are two ways of signing up in the Marketplace:

2022-10-17 21:55 UTC, georgiana-caras commented on content/en/docs/manage_marketplace/consumer_experience/_index.md
> +* a provider invited you in his organization
a provider invited you into his/her organization

2022-10-17 21:55 UTC, georgiana-caras commented on content/en/docs/manage_marketplace/consumer_experience/_index.md
> +* provider decided to let his consumer to self signup to the marketplace and manage their [organization, users and teams](/docs/manage_marketplace/consumer_experience/consumer_organization)
consumers can self register to the Marketplace  and manage their [organization, users and teams](/docs/manage_marketplace/consumer_experience/consumer_organization)

2022-10-17 21:55 UTC, georgiana-caras commented on content/en/docs/manage_marketplace/consumer_experience/consumer_organization.md
> +The first time a user sign up to a marketplace, he has to enter the following information in the displayed form to create his account:
The first time a user signs up to a marketplace, she must enter the following information in the sign up form:

2022-10-17 21:55 UTC, georgiana-caras commented on content/en/docs/manage_marketplace/consumer_experience/consumer_organization.md
> +* Email - email address that will be use later to login to the marketplace
email address that will be used to login to the marketplace

2022-10-17 21:55 UTC, georgiana-caras commented on content/en/docs/manage_marketplace/consumer_experience/consumer_organization.md
> +* Organization - the name of the organization that will be created and reference as a consumer organization
referenced

2022-10-17 21:55 UTC, georgiana-caras commented on content/en/docs/manage_marketplace/consumer_experience/consumer_organization.md
> +A consumer organization allows you to defines users and teams. Each user can have one or more role. Each can be part of one or multiple teams.
A user can have one or more role assigned, and can be a member of multiple teams.

2022-10-17 21:55 UTC, georgiana-caras commented on content/en/docs/manage_marketplace/consumer_experience/consumer_organization.md
> +The first user who creates the organization is the **Administrator** of the organization. This administrator can change the roles of the users, with the restriction that there always needs to be at l
The user that registered with a consumer organization will become the **Administrator** of the organization. The administrator can manage the user roles, under the condition that there always must be a user that has the administrator role assigned.

2022-10-17 21:55 UTC, georgiana-caras commented on content/en/docs/manage_marketplace/consumer_experience/consumer_organization.md
> +    * **Consumer** - allow to consumer product in marketplace
consume products

2022-10-17 21:55 UTC, georgiana-caras commented on content/en/docs/manage_marketplace/consumer_experience/consumer_organization.md
> +    * **Consumer** - allow to manage free plan subscription, product access and credentials and application
and to manage their applications

2022-10-17 21:55 UTC, georgiana-caras commented on content/en/docs/manage_marketplace/consumer_experience/consumer_organization.md
> +    * **Team Manager** - allow to organize the team: add/remove existing user
allow to manage the team by adding or removing users

2022-10-17 21:55 UTC, georgiana-caras commented on content/en/docs/manage_marketplace/consumer_experience/consumer_organization.md
> +    * **Subscriber** - allows to manage the paid plan subscription
allows to subscribe to paid plans and manage paid subscriptions.

2022-10-17 21:55 UTC, georgiana-caras commented on content/en/docs/manage_marketplace/consumer_experience/consumer_organization.md
> +A team is a logical grouping of users. The idea is to enable you to create teams so that certain groups of people can work together or have access to the same set of Marketplace product. The same use
remove 'each organization always has a default team'

2022-10-17 21:55 UTC, georgiana-caras commented on content/en/docs/manage_marketplace/consumer_experience/consumer_organization.md
> +A team is a logical grouping of users. The idea is to enable you to create teams so that certain groups of people can work together or have access to the same set of Marketplace product. The same use
A team is a logical grouping of users that allows certain group of members to collaborate on the consumption of a product and building an application, but accessing same set of subscriptions, credentials and applications. A user can belong to multiple teams and have different roles assigned in each team.

2022-10-17 21:55 UTC, georgiana-caras commented on content/en/docs/manage_marketplace/consumer_experience/consumer_organization.md
> +Only Administrator and Team Manager can create/view/edit/delete any team. But, the default team cannot be deleted. There should always be a Default team in an organization.
Each organization must have a default team.  Default team cannot be deleted.

2022-10-17 21:55 UTC, georgiana-caras commented on content/en/docs/manage_marketplace/consumer_experience/consumer_organization.md
> +For Adding a user to the current organization, Administrator has to invite the user.
A new user can be added to the organization by sending an invite.

2022-10-17 21:55 UTC, georgiana-caras commented on content/en/docs/manage_marketplace/consumer_experience/consumer_organization.md
> +3. A new screen is displayed where Administrator has to enter the user email and provide him the appropriate roles (Organization role and Team roles).
Administrator must enter the user email and assign the appropriate Organization and Team roles.

2022-10-17 21:55 UTC, georgiana-caras commented on content/en/docs/manage_marketplace/consumer_experience/consumer_organization.md
> +4. Click Save when done and the user will receive the invite email.
the email invite.

2022-10-17 21:55 UTC, georgiana-caras commented on content/en/docs/manage_marketplace/consumer_experience/consumer_organization.md
> +Team Administrator can only add/remove members from the team they are part of.
A Team Administrator can only add or remove members in the team they belong to.

2022-10-17 21:55 UTC, georgiana-caras commented on content/en/docs/manage_marketplace/consumer_experience/consumer_organization.md
> +3. A confirmation popup is displayed for the user to validate the action to be sure he wants to replace the existing default team
A confirmation popup is displayed for the user to validate the action

2022-10-17 21:55 UTC, georgiana-caras commented on content/en/docs/manage_marketplace/consumer_experience/consumer_organization.md
> +4. Once the action is validated, the current team is now set a the Default team
as the Default team

2022-10-17 21:55 UTC, georgiana-caras commented on content/en/docs/manage_marketplace/marketplace_consumer_organization.md
> +Provider can provide one or more Consumer organization that are independently managed from his own organization
Providers can configure one or more Consumer organizations that are independently managed from their own provider organization.

2022-10-17 21:55 UTC, georgiana-caras commented on content/en/docs/manage_marketplace/marketplace_consumer_organization.md
> +For instance, if you have a partner and you don't want to manage their users in your provider organization, you can let them have their own Consumer organization. Like this your partner becomes self-
We should remove this entire paragraph.

2022-10-17 21:55 UTC, georgiana-caras commented on content/en/docs/manage_marketplace/marketplace_consumer_organization.md
> +This page displays all the Consumer organization available with their number of teams and users. Provider is not able to add teams or users to those organizations and can only enable/disable them.
A provider does not have the rights to add teams or users into a consumer organization. The only actions they are allowed to perform is Enable/Disable organizations.

2022-10-17 21:55 UTC, georgiana-caras commented on content/en/docs/manage_marketplace/marketplace_consumer_organization.md
> +Only Enabled organization allows user to connect to the Marketplace.
Disabling a Consumer Organization will stop users registered in that organization to connect to the Marketplace.

2022-10-17 21:55 UTC, georgiana-caras commented on content/en/docs/manage_marketplace/marketplace_consumer_organization.md
> +Select an active organization you want to disable and clicks the ellipsis menu / Disable. A confirmation popup is displayed. Clicking the **Disable** button will trigger the action and the organizati
click

2022-10-17 21:55 UTC, georgiana-caras commented on content/en/docs/manage_marketplace/marketplace_settings.md
> +        * **Disallow** - nobody can signup to the Marketplace and only Administrator can invite users to ths Marketplace.
**Disallow** - self-signup is disabled  and only Administrators can invite users into the Marketplace.

2022-10-17 21:55 UTC, georgiana-caras commented on content/en/docs/manage_marketplace/marketplace_settings.md
> +        * **Allow** - anyone can signup to the Marketplace and register their own account. They will receive and email to activate their account.
remove *They will receive and email to activate their account* as it is not relevant here

2022-10-18 19:11 UTC, lbadenhop approved these changes

2022-10-19 21:03 UTC, merged