Vanity url
Axway/amplify-central pull request #227
Opened 2022-11-28 23:18 UTC by cbordier

Thank you for your contribution to the Amplify-Central repo.

## Describe the changes

Add vanity url explanation and how to mange the certificate

## Checklist for contributors

Before submitting this PR, please make sure:

* [X] You have read the [contribution guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/)
* [X] You have signed the [Axway CLA](https://cla.axway.com/)
* [X] You have verified the technical accuracy of your change
* [X] You have verified that your change does not expose any sensitive information (passwords, keys, etc.)
* [X] You have followed the [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)  (unless this is is a Netlify CMS contribution)

_Put an x in the boxes that apply. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your change._

2022-11-29 13:45 UTC, cbordier commented
@lbadenhop, it is ready for your review.

2022-11-29 23:01 UTC, georgiana-caras requested changes
@cbordier, have suggested some changes to the content,

2022-11-29 23:01 UTC, georgiana-caras commented on content/en/docs/manage_marketplace/marketplace_vanity_url.md
> +Using your marketplace URL, you should be able to access the marketplace homepage.
Navigate your custom marketplace URL to validate that the changes have been applied successfully.

2022-12-01 00:40 UTC, lbadenhop approved these changes

2022-12-01 00:42 UTC, merged