APIGOV-24237 Document Access request management
Axway/amplify-central pull request #232
Opened 2022-12-07 22:04 UTC by cbordier

Thank you for your contribution to the Amplify-Central repo.

## Describe the changes

Add Access request management for Provider and refactor Consumer experience

## Checklist for contributors

Before submitting this PR, please make sure:

* [X] You have read the [contribution guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/)
* [X] You have signed the [Axway CLA](https://cla.axway.com/)
* [X] You have verified the technical accuracy of your change
* [X] You have verified that your change does not expose any sensitive information (passwords, keys, etc.)
* [X] You have followed the [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)  (unless this is is a Netlify CMS contribution)

_Put an x in the boxes that apply. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your change._

2023-01-10 16:57 UTC, georgiana-caras requested changes

2023-01-10 16:57 UTC, georgiana-caras commented on content/en/docs/manage_marketplace/manage_subscribers_subscriptions.md
> +* Approving / rejecting Request access
Approving / rejecting Access requests

2023-01-10 16:57 UTC, georgiana-caras commented on content/en/docs/manage_marketplace/manage_subscribers_subscriptions.md
> +The subscription list can be filter per subscription status (Pending / Approved / Rejected) and/or per team.
can be filtered

2023-01-10 16:57 UTC, georgiana-caras commented on content/en/docs/manage_marketplace/manage_subscribers_subscriptions.md
> +Each subscription displays its name, the associated product, the organization and team that owned the subscription and the approval status.
displays the name

2023-01-10 16:57 UTC, georgiana-caras commented on content/en/docs/manage_marketplace/manage_subscribers_subscriptions.md
> +Clicking on subscription name opens the side blade with the subscription detail information. From this screen, once his consumer met all the requirements that are needed to bill him, subscrition appr
Clicking on subscription name opens the side blade with the subscription details. From this screen, the subscription approver can approve the subscription by using the **Approve** button.

2023-01-10 16:57 UTC, georgiana-caras commented on content/en/docs/manage_marketplace/manage_subscribers_subscriptions.md
> +The subscription list can be filter per subscription status (Pending / Approved / Rejected) and/or per team.
can be filtered by

2023-01-10 16:57 UTC, georgiana-caras commented on content/en/docs/manage_marketplace/manage_subscribers_subscriptions.md
> +Each subscription displays its name, the associated product, the organization and team that owned the subscription and the approval status.
displays the name

2023-01-10 16:57 UTC, georgiana-caras commented on content/en/docs/manage_marketplace/manage_subscribers_subscriptions.md
> +Catalog manager needs to navigate to Amplify Central > Marketplace > Access Requests to view all access request he can manage.
she can manage

2023-01-10 16:57 UTC, georgiana-caras commented on content/en/docs/manage_marketplace/manage_subscribers_subscriptions.md
> +Each access request displays its name, the associated asset, the organization ot the team that owned the request, the approval status and the provisioning status.
displays the name, the associated product, the organization of the team

2023-01-10 16:57 UTC, georgiana-caras commented on content/en/docs/manage_marketplace/manage_subscribers_subscriptions.md
> +Catalog manager needs to navigate to Amplify Central > Marketplace > Access Requests to view all access request he can manage.
she can manage

2023-01-10 16:57 UTC, georgiana-caras commented on content/en/docs/manage_marketplace/manage_subscribers_subscriptions.md
> +Clicking on access request name opens the side blade with the access request detail information. From this screen, catalog manager can reject the access request using the **Revoke** button in case th
with the access request details. From this screen a catalog manager can reject the access request using the **Revoke** button in case the access request was approved previously or the **Decline** button in case the access request is pending.

2023-01-11 04:20 UTC, lbadenhop approved these changes

2023-01-11 04:24 UTC, lbadenhop commented
@cbordier, please review my edits, especially to manage_subscribers_subscriptions. Thanks

2023-01-11 15:43 UTC, cbordier reviewed
I approve the changes

2023-01-11 15:45 UTC, merged