APIGOV-24234 Edit assets and products without requiring a new re…
Axway/amplify-central pull request #233
Opened 2022-12-07 22:53 UTC by lbadenhop

…lease

Thank you for your contribution to the Amplify-Central repo.

## Describe the changes

Enter a brief description of your changes here to communicate to the maintainers what you changed and why.

## Checklist for contributors

Before submitting this PR, please make sure:

* [ ] You have read the [contribution guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/)
* [ ] You have signed the [Axway CLA](https://cla.axway.com/)
* [ ] You have verified the technical accuracy of your change
* [ ] You have verified that your change does not expose any sensitive information (passwords, keys, etc.)
* [ ] You have followed the [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)  (unless this is is a Netlify CMS contribution)

_Put an x in the boxes that apply. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your change._

2022-12-09 20:50 UTC, georgiana-caras requested changes

2022-12-09 20:50 UTC, georgiana-caras commented on content/en/docs/manage_asset_catalog/asset_management.md
>  ## Activate an asset
@robertengaxway , maybe we should rename this section to Edit an asset to better reflect the content of the section. The content describes more how to edit the asset.

2022-12-12 23:10 UTC, lbadenhop commented
@robertengaxway Please review my edits.

2022-12-12 23:11 UTC, lbadenhop commented on content/en/docs/manage_asset_catalog/asset_management.md
>  ## Activate an asset
I don't understand why you want to rename Activate an Asset to Edit and asset. There is already an Edit an Asset section.

2022-12-14 20:20 UTC, robertengaxway commented on content/en/docs/manage_asset_catalog/asset_management.md
>  ## Activate an asset
@georgiana-caras  The "Edit an asset" is subsection of "Asset Management".   There are other subsections for create, activate, and organize.   Activation is a separate action after creating a draft or changing an asset from Deprecated.   
I think the current "Edit an asset" subsection title is in the correct place

2022-12-15 15:57 UTC, robertengaxway approved these changes
I approve

2022-12-15 17:56 UTC, georgiana-caras requested changes
Overall there are not many things to change, see inline comments. For the product foundry most of the text in preview appears bold, there seems to be an syntax error in the markdown file

2022-12-15 17:56 UTC, georgiana-caras commented on content/en/docs/manage_asset_catalog/asset_management.md
>  7. Configure the Access Request handling, Manual or Automatic, and click **Next**.
@robertengaxway , you could explain what the Access Request handling is for, the way you did for the auto-release.

2022-12-15 17:56 UTC, georgiana-caras commented on content/en/docs/manage_asset_catalog/asset_management.md
> +8. At the Access Rights step, select the team(s) the asset can be shared with. By default, an asset is not shared and only the **Central Admin** will have access to it. If you shared your asset with
team will be able to see your asset (not product)

2022-12-15 17:56 UTC, georgiana-caras commented on content/en/docs/manage_product_foundry/foundry_product_management.md
> +You must have credentials or a user account from your org administrator to use the Product Foundry WebUI. Please follow the steps [here](https://docs.axway.com/bundle/platform-management/page/docs/ma
To be replaced with: You must have the Catalog Manager team role assigned by tour organization administrator in order to use the Product Foundry. Please follow the steps [here](https://docs.axway.com/bundle/platform-management/page/docs/management_guide/organizations/managing_organizations/index.html#managing-users).

2022-12-15 17:56 UTC, georgiana-caras commented on content/en/docs/manage_product_foundry/foundry_product_management.md
> +    * Auto-Release - Enabled/Disabled of the auto release of new Product versions. If auto-release is **enabled**, a new product will be automatically released with each change to any one of the link
Typo prodcut

2022-12-15 18:07 UTC, robertengaxway commented on content/en/docs/manage_asset_catalog/asset_management.md
>  7. Configure the Access Request handling, Manual or Automatic, and click **Next**.
done

2022-12-15 18:08 UTC, robertengaxway commented on content/en/docs/manage_asset_catalog/asset_management.md
> +8. At the Access Rights step, select the team(s) the asset can be shared with. By default, an asset is not shared and only the **Central Admin** will have access to it. If you shared your asset with
fixed

2022-12-15 18:10 UTC, robertengaxway commented on content/en/docs/manage_product_foundry/foundry_product_management.md
> +You must have credentials or a user account from your org administrator to use the Product Foundry WebUI. Please follow the steps [here](https://docs.axway.com/bundle/platform-management/page/docs/ma
done

2022-12-15 18:10 UTC, robertengaxway commented on content/en/docs/manage_product_foundry/foundry_product_management.md
> +    * Auto-Release - Enabled/Disabled of the auto release of new Product versions. If auto-release is **enabled**, a new product will be automatically released with each change to any one of the link
done

2022-12-15 18:13 UTC, robertengaxway approved these changes

2022-12-15 23:17 UTC, merged