January 12, 2023 Release Notes
Axway/amplify-central pull request #249
Opened 2023-01-11 22:26 UTC by lbadenhop

Thank you for your contribution to the Amplify-Central repo.

## Describe the changes

Enter a brief description of your changes here to communicate to the maintainers what you changed and why.

## Checklist for contributors

Before submitting this PR, please make sure:

* [ ] You have read the [contribution guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/)
* [ ] You have signed the [Axway CLA](https://cla.axway.com/)
* [ ] You have verified the technical accuracy of your change
* [ ] You have verified that your change does not expose any sensitive information (passwords, keys, etc.)
* [ ] You have followed the [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)  (unless this is is a Netlify CMS contribution)

_Put an x in the boxes that apply. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your change._

2023-01-11 22:32 UTC, lbadenhop commented
@cbordier, @robertengaxway, @georgiana-caras - Ready for content

2023-01-13 22:10 UTC, robertengaxway approved these changes
I approve

2023-01-13 22:12 UTC, georgiana-caras requested changes

2023-01-13 22:12 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20230112_amplify.md
> +* **Long product name are badly displayed when Activating the product** - Long product name are no more truncated when activating a product version.
**Long product names are not properly displayed when activating a product** - Long product names are no longer truncated  when activating a product version.

2023-01-13 22:12 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20230112_amplify.md
> +* **Permission issue when editing product and asset has read-only access** - The Asset name attached to a product are always visible. In case the user cannot access it, the link will be disable
Prior to the fix, an user that had edit rights on a product that contained an asset that was shared with his / her team in read-only mode,  could not see the asset name. After the fix, the asset name is visible. In situations where the user does not have access to the asset, the link will be disabled so they cannot see the details of the asset.

2023-01-13 22:12 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20230112_amplify.md
> +* **Switching back and force between paid and free plan in the wizard does not create the plan correctly** - The wizard page navigation is now correctly handled and the plan is created according to t
**Switching back and fort between a paid and a free plan in the wizard does not create the plan correctly**

2023-01-13 22:12 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20230112_amplify.md
> +* **Support contact long name no well no visible in marketplace** - Now the support contact name is truncated based on the space available to display it and a tooltip shows its entire value.
**Long support contact name not properly displayed in the Marketplace** - Long support contact names are not truncated to fit on the screen and a tool tip has been added to show the entire value when user hovers over it.

2023-01-13 22:12 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20230112_amplify.md
> +* **The section navigation in documentation is broken when using special characters ('?', '#', '/'...)** - The special characters are now accepted in documentation section and does not break the navi
**The navigation section in the documentation is broken when using special characters ('?', '#', '/'...)**

2023-01-13 22:15 UTC, georgiana-caras requested changes

2023-01-13 22:15 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20230112_amplify.md
> +* **Duplicate API Service Revisions** - There was a fix to not create duplicate API service revisions when restrating the Discovery agent.
when restarting the Discovery agent.

2023-01-13 22:15 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20230112_amplify.md
> +* **Asset archival from UI** - From the webUI Asset Catalog, the ellipsis menu allows an asset to be archived.   All asset releases will be moved to an arhived state as long as there are no assoicate
typo **arhived**

2023-01-13 22:15 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20230112_amplify.md
> +* **Asset Creation UI** - A fix was made to the Asset creation UI wizard to without generating an error message when saving the asset.
I don;t understand what was generating the error.

2023-01-13 22:15 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20230112_amplify.md
> +* **Asset status Ui** - A fix was made to update the Asset version status and the overall Asset status in a more timely fashion.
UI

2023-01-17 22:38 UTC, cbordier approved these changes
I approve the changes

2023-01-18 03:28 UTC, merged