APIGOV-24325 - Migrating plan
Axway/amplify-central pull request #260
Opened 2023-02-01 18:27 UTC by cbordier

Thank you for your contribution to the Amplify-Central repo.

## Describe the changes

Adding the missing action for product plan

## Checklist for contributors

Before submitting this PR, please make sure:

* [X] You have read the [contribution guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/)
* [X] You have signed the [Axway CLA](https://cla.axway.com/)
* [X] You have verified the technical accuracy of your change
* [X] You have verified that your change does not expose any sensitive information (passwords, keys, etc.)
* [X] You have followed the [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)  (unless this is is a Netlify CMS contribution)

_Put an x in the boxes that apply. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your change._

2023-02-01 18:29 UTC, docsbuilder commented
### <span aria-hidden="true">✅</span> Deploy preview is ready!

 |  Name | Link |
 |---------------------------------|------------------------|
 |<span aria-hidden="true">🔨</span> Latest commit | 382bafe |
 |<span aria-hidden="true">😎</span> Deploy preview | http://PR-260.amplify-central.opendocs-builder.pcloud.axway.int |

2023-02-14 19:38 UTC, georgiana-caras requested changes

2023-02-14 19:38 UTC, georgiana-caras commented on content/en/docs/manage_product_foundry/manage_product_plans.md
> +A provider can decide to deprecate an active plan as it is no move relevant for his subscribers. Once the action is initiated, provider will face multiple choices:
A provider can deprecate an active plan when is terms of the plan changes or it is no longer relevant and they would like to prevent new subscriptions under the plan.  When deprecating a plan, the user can choose from the following options:

2023-02-14 19:38 UTC, georgiana-caras commented on content/en/docs/manage_product_foundry/manage_product_plans.md
> +* **Deprecate the plan only** - this plan will no more be available for any new subscriber but existing subscription with this plan are still valid.
this plan will no longer be available for new subscriptions, but existing ones will continue to work.

2023-02-14 19:38 UTC, georgiana-caras commented on content/en/docs/manage_product_foundry/manage_product_plans.md
> +* **Cancel the corresponding subscription** - the corresponding subscription will be cancelled and cannot be use anymore to request resource access. But the subscription is still present in the Marke
the corresponding subscription will be cancelled and cannot be used anymore to request resource access; the subscription is still present in the Marketplace so that the associated metrics can be displayed.

2023-02-14 19:38 UTC, georgiana-caras commented on content/en/docs/manage_product_foundry/manage_product_plans.md
> +* **Migrate subscription to a new plan** - the existing plan subscription will be move to a new plan. Refer to [Migrate subscriptions to a new plan](/docs/manage_product_foundry/manage_product_plans#
the subscriptions under this plan will be moved to a new plan. Refer to [Migrate subscriptions to a new plan](/docs/manage_product_foundry/manage_product_plans#migrate-subscriptions-to-a-new-plan).

2023-02-14 19:38 UTC, georgiana-caras commented on content/en/docs/manage_product_foundry/manage_product_plans.md
> +
To deprecate a plan:

2023-02-14 19:38 UTC, georgiana-caras commented on content/en/docs/manage_product_foundry/manage_product_plans.md
> +5. Select the action: None, Move to a new Plan or Cancel.
Move to a new plan

2023-02-14 19:38 UTC, georgiana-caras commented on content/en/docs/manage_product_foundry/manage_product_plans.md
> +Once this plan is deprecated, Marketplace consumers cannot subscribe to it anymore. Only subscribers having an active subscription with this plan can see it.
Only subscribers having an active subscription under this plan can see it.

2023-02-14 19:38 UTC, georgiana-caras commented on content/en/docs/manage_product_foundry/manage_product_plans.md
> +Providers get consumers on a new plan when the terms change (a change in the quota, price, resources) by migrating existing subscriptions to a another plan. When subscriptions are migrated, the issue
Providers can get consumers

2023-02-14 20:30 UTC, cbordier reviewed
@lbadenhop, I already integrated Georgie's comments
Ready for your review.

2023-02-15 17:39 UTC, lbadenhop commented
@cbordier, do you want to review my edits before I merge?

2023-02-15 18:27 UTC, cbordier commented on content/en/docs/manage_product_foundry/manage_product_plans.md
> +A provider can deprecate an active plan when the terms of the plan change, or it is no longer relevant, and they would like to prevent new subscriptions under the plan. When deprecating a plan, the p
@lbadenhop 
"the provider can choose one of the following **subscription migrations**:"

It is not always a subscription migration in the choices. 
Maybe it is better to say: **one of the following plan termination:**

2023-02-15 18:43 UTC, merged