Publish to Marketplace content
Axway/amplify-central pull request #261
Opened 2023-02-02 17:35 UTC by lbadenhop

Thank you for your contribution to the Amplify-Central repo.

## Describe the changes

Enter a brief description of your changes here to communicate to the maintainers what you changed and why.

## Checklist for contributors

Before submitting this PR, please make sure:

* [ ] You have read the [contribution guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/)
* [ ] You have signed the [Axway CLA](https://cla.axway.com/)
* [ ] You have verified the technical accuracy of your change
* [ ] You have verified that your change does not expose any sensitive information (passwords, keys, etc.)
* [ ] You have followed the [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)  (unless this is is a Netlify CMS contribution)

_Put an x in the boxes that apply. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your change._

2023-02-02 17:38 UTC, docsbuilder commented
### <span aria-hidden="true">✅</span> Deploy preview is ready!

 |  Name | Link |
 |---------------------------------|------------------------|
 |<span aria-hidden="true">🔨</span> Latest commit | cd74d1e |
 |<span aria-hidden="true">😎</span> Deploy preview | http://PR-261.amplify-central.opendocs-builder.pcloud.axway.int |

2023-02-15 16:55 UTC, lbadenhop commented
@georgiana-caras, please approve content before I review and merge. Thanks.

2023-02-16 21:10 UTC, georgiana-caras requested changes

2023-02-16 21:10 UTC, georgiana-caras commented on content/en/docs/manage_service_registry/service_management.md
> +## Publish to the Marketplace
Publish to Marketplace from the Service Registry enables providers to quickly promote an API to the Marketplace for internal consumption as a product under a Free plan. An asset and a product will automatically be generated. The publication is initially restricted to teams in the provider organization, but changes can be made to the product from the Product Foundry at any point in time.

2023-02-16 21:10 UTC, georgiana-caras commented on content/en/docs/manage_service_registry/service_management.md
> +5. Click **Publish** to quickly make an API service available from consumption in the Marketplace.
API Service available for consumption

2023-02-17 12:51 UTC, merged