February 10 Release Notes
Axway/amplify-central pull request #263
Opened 2023-02-06 17:49 UTC by lbadenhop

Thank you for your contribution to the Amplify-Central repo.

## Describe the changes

Enter a brief description of your changes here to communicate to the maintainers what you changed and why.

## Checklist for contributors

Before submitting this PR, please make sure:

* [ ] You have read the [contribution guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/)
* [ ] You have signed the [Axway CLA](https://cla.axway.com/)
* [ ] You have verified the technical accuracy of your change
* [ ] You have verified that your change does not expose any sensitive information (passwords, keys, etc.)
* [ ] You have followed the [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)  (unless this is is a Netlify CMS contribution)

_Put an x in the boxes that apply. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your change._

2023-02-06 17:52 UTC, docsbuilder commented
### <span aria-hidden="true">✅</span> Deploy preview is ready!

 |  Name | Link |
 |---------------------------------|------------------------|
 |<span aria-hidden="true">🔨</span> Latest commit | e1fdfb1 |
 |<span aria-hidden="true">😎</span> Deploy preview | http://PR-263.amplify-central.opendocs-builder.pcloud.axway.int |

2023-02-10 14:02 UTC, robertengaxway approved these changes
I approve

2023-02-10 18:12 UTC, cbordier approved these changes
I approve the changes

2023-02-10 19:03 UTC, georgiana-caras requested changes
Requested some changes

2023-02-10 19:03 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20230210_amplify.md
> +* **Subscriptions data can be exported as a CSV file** - Provider can export to a CSV file the data they see on Business Insights / Subscriptions using the 3 dots beside the time filter.
A provider can export the subscription records in Business Insights to a CSV file by using the ellipses menu located next to the time filter.

2023-02-10 19:03 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20230210_amplify.md
> +* **Large number of application showing "Unknown"** - The transactions that are not initiated from a Marketplace subscription are now removed from the Application and Subscription screens.
Large number of applications showing "Unknown"

2023-02-10 19:03 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20230210_amplify.md
> +* **Deprecated / archived plan is still available for subscription** - The deprecate/archived plans are no more available when consumer initiate a subscription.
Consumers can no longer subscribe to a plan that is either deprecated or archived.

2023-02-10 19:03 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20230210_amplify.md
> +* **Corrupted product does not show the warning icon in all marketplaces** - The corrupted product are displayed with the warning icon in all marketplaces the product is deployed on.
A corrupted product now shows a warning icon in all Marketplaces it is published into.

2023-02-11 01:16 UTC, merged