API Service detail enhancement
Axway/amplify-central pull request #265
Opened 2023-02-09 18:26 UTC by lbadenhop

Thank you for your contribution to the Amplify-Central repo.

## Describe the changes

Enter a brief description of your changes here to communicate to the maintainers what you changed and why.

## Checklist for contributors

Before submitting this PR, please make sure:

* [ ] You have read the [contribution guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/)
* [ ] You have signed the [Axway CLA](https://cla.axway.com/)
* [ ] You have verified the technical accuracy of your change
* [ ] You have verified that your change does not expose any sensitive information (passwords, keys, etc.)
* [ ] You have followed the [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)  (unless this is is a Netlify CMS contribution)

_Put an x in the boxes that apply. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your change._

2023-02-09 18:27 UTC, docsbuilder commented
### <span aria-hidden="true">✅</span> Deploy preview is ready!

 |  Name | Link |
 |---------------------------------|------------------------|
 |<span aria-hidden="true">🔨</span> Latest commit | 0c59b70 |
 |<span aria-hidden="true">😎</span> Deploy preview | http://PR-265.amplify-central.opendocs-builder.pcloud.axway.int |

2023-02-14 15:16 UTC, georgiana-caras requested changes

2023-02-14 15:16 UTC, georgiana-caras commented on content/en/docs/manage_service_registry/service_management.md
> +* The general Tags & Attribues tab displays the tags and attributes properties for the general API Service.
Tags & Attributes

2023-02-14 15:16 UTC, georgiana-caras commented on content/en/docs/manage_service_registry/service_management.md
> +* The general Asset tab displays all the Assets which are grouped with this general API Service.
The general Asset tab displays all the Assets that contain this API Service.

2023-02-14 16:16 UTC, merged