February 24 Release Notes
Axway/amplify-central pull request #268
Opened 2023-02-22 21:17 UTC by lbadenhop

Thank you for your contribution to the Amplify-Central repo.

## Describe the changes

Enter a brief description of your changes to communicate to the reviewers what you changed and why.

## Deploy preview link

Please add the deploy preview link to the **specific page** that you've changed.

## Checklist for contributors

Before submitting this PR:

* Verify that all status checks have passed
* For more information on the Markdown linter rules, see [DavidAnson/markdownlint](https://github.com/DavidAnson/markdownlint)
* For first-time contributors, ensure that you have signed the [Axway CLA](https://cla.axway.com/)

2023-02-22 21:20 UTC, docsbuilder commented
### <span aria-hidden="true">✅</span> Deploy preview is ready!

 |  Name | Link |
 |---------------------------------|------------------------|
 |<span aria-hidden="true">🔨</span> Latest commit | 4ed6abb |
 |<span aria-hidden="true">😎</span> Deploy preview | http://PR-268.amplify-central.opendocs-builder.pcloud.axway.int |

2023-02-24 23:01 UTC, georgiana-caras requested changes

2023-02-24 23:01 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20230224_amplify.md
> +* **Category table listing cannot navigate to any page the first time** - Now the pagination of category list, plan list allows to navigate from one page to another.
**Pagination issue in the category list view and plan list view* - Prior to this fix, the user could not navigate to other list pages using the pagination controller, resulting in the user always seeing the records displayed on the first page. After the fix, they can use the pagination controller to jump to any page.

2023-02-25 01:00 UTC, cbordier approved these changes
I approve the changes

2023-02-25 01:04 UTC, merged