New topic - Add your environment
Axway/amplify-central pull request #291
Opened 2023-04-27 20:56 UTC by lbadenhop

Thank you for your contribution to the Amplify-Central repo.

## Describe the changes

Enter a brief description of your changes to communicate to the reviewers what you changed and why.

## Deploy preview link

Please add the deploy preview link to the **specific page** that you've changed.

## Checklist for contributors

Before submitting this PR:

* Verify that all status checks have passed
* For more information on the Markdown linter rules, see [DavidAnson/markdownlint](https://github.com/DavidAnson/markdownlint)
* For first-time contributors, ensure that you have signed the [Axway CLA](https://cla.axway.com/)

2023-04-27 20:58 UTC, docsbuilder commented
### <span aria-hidden="true">✅</span> Deploy preview is ready!

 |  Name | Link |
 |---------------------------------|------------------------|
 |<span aria-hidden="true">🔨</span> Latest commit | ea44eef |
 |<span aria-hidden="true">😎</span> Deploy preview | http://PR-291.amplify-central.opendocs-builder.pcloud.axway.int |

2023-05-02 15:17 UTC, jcollins-axway commented on content/en/docs/connect_manage_environ/add_environments.md
> +4. Configuration (Optionally displayed stesp if there is Embedded Agent support for the selected Environment Type)
stesp*

2023-05-02 15:20 UTC, jcollins-axway commented on content/en/docs/connect_manage_environ/add_environments.md
> +    * **Agent Type** - select the type of agent to be be used to connect to this API Gateway.  Select **Embedded** for Axway to host the agent in the Amplify Managed Cloud or select **Remotely Hosted
If Managed Cloud is hosing the agent, won't they be installing this? Just wondering if we should tell the user to select "Remotely Hosted" hear with the note that "Embedded" is for Amplify Managed Cloud hosted environments?

2023-05-02 15:23 UTC, jcollins-axway commented on content/en/docs/connect_manage_environ/add_environments.md
> +    * **Agent Configuration** - This is only displayed for the Embedded Agent Type of AWS API Gateway.
2 things. 

For all the steps on the Environment profile page the field is bolded and the info starts lowercase, in this section the field is still bolded but the info starts Uppercase.

Rather than requiring a future update, can this just call out Supported Environment Types instead of AWS API Gateway Specifically.  However the fields will change based off the gateway.

2023-05-02 15:24 UTC, jcollins-axway commented on content/en/docs/connect_manage_environ/add_environments.md
> +         * **AWS Authentication** - Select the method of AWS Authentication to use, AssmeRole or Access Key/Secret Key.  For additional information on how to create either the AssumeRole (AWS IAM rol
AssmeRole*

2023-05-02 15:26 UTC, jcollins-axway requested changes
comments made on requested changes

2023-05-02 16:57 UTC, robertengaxway commented on content/en/docs/connect_manage_environ/add_environments.md
> +    * **Agent Type** - select the type of agent to be be used to connect to this API Gateway.  Select **Embedded** for Axway to host the agent in the Amplify Managed Cloud or select **Remotely Hosted
I was trying to explain the meaning of two choices which can still be made here. 
do you have a suggestion on how to make the choices clearer?

2023-05-02 17:24 UTC, jcollins-axway commented on content/en/docs/connect_manage_environ/add_environments.md
> +    * **Agent Type** - select the type of agent to be be used to connect to this API Gateway.  Select **Embedded** for Axway to host the agent in the Amplify Managed Cloud or select **Remotely Hosted
I would think something blunt such as

select "Remotely Hosted" here. The "Embedded" option is used only for Amplify Managed Cloud hosted environments.

2023-05-02 17:28 UTC, jcollins-axway commented on content/en/docs/connect_manage_environ/add_environments.md
> +    * **Agent Type** - select the type of agent to be be used to connect to this API Gateway.  Select **Embedded** for Axway to host the agent in the Amplify Managed Cloud or select **Remotely Hosted
I got things confused here, maybe just drop "in the Amplify Managed Cloud" as Axway to host the agent should be enough.

2023-05-02 20:38 UTC, cbordier approved these changes
I approve the changes

2023-05-03 18:01 UTC, merged