Compliance section
Axway/amplify-central pull request #303
Opened 2023-05-16 19:45 UTC by lbadenhop

Thank you for your contribution to the Amplify-Central repo.

## Describe the changes

Enter a brief description of your changes to communicate to the reviewers what you changed and why.

## Deploy preview link

Please add the deploy preview link to the **specific page** that you've changed.

## Checklist for contributors

Before submitting this PR:

* Verify that all status checks have passed
* For more information on the Markdown linter rules, see [DavidAnson/markdownlint](https://github.com/DavidAnson/markdownlint)
* For first-time contributors, ensure that you have signed the [Axway CLA](https://cla.axway.com/)

2023-05-16 19:47 UTC, docsbuilder commented
### <span aria-hidden="true">✅</span> Deploy preview is ready!

 |  Name | Link |
 |---------------------------------|------------------------|
 |<span aria-hidden="true">🔨</span> Latest commit | bc948f6 |
 |<span aria-hidden="true">😎</span> Deploy preview | http://PR-303.amplify-central.opendocs-builder.pcloud.axway.int |

2023-05-18 20:59 UTC, feons commented on content/en/docs/manage_compliance/_index.md
> +The Amplify API Management Platmform allows you to validate how well your APIs meet the API guidelines of your organization.   This is known as API linting and has been integrated into the Amplify AP
'Compliance Validation is an entitlement you can purchase API Management.' ??

2023-05-18 21:00 UTC, feons commented on content/en/docs/manage_compliance/_index.md
> +Compliance validation is the verification of your APIs in terms of how thy meeet the guidelines defined in a rule set.  Both an API Design and Security rule set can be applied to all the APIs in a se
thy?

2023-05-18 21:02 UTC, feons commented on content/en/docs/manage_compliance/_index.md
> +For example, an API can be checked for compliance in terms of the API methods supported or the presence of a security policy.  The gradiing results of the compliance are measured in the number of Err
typo: gradiing?

2023-05-18 21:05 UTC, jquick-axway requested changes

2023-05-18 21:05 UTC, jquick-axway commented on content/en/docs/manage_compliance/_index.md
> +API Compliance Validation can be enabled/disabled per Environment.   Navigate to the Topology screen then create/edit an environment.   The environment wizard with have a **Compliance Profile** step,
Sentence "The environment wizard `with` have a Compliance Profile..." should be "The environment wizard `will` have a Compliance Profile...". Notice the change from "with" to "will".

2023-05-18 21:13 UTC, lbadenhop commented
@robertengaxway I created the table and fixed a few typos. I review/edit once you are done.

2023-05-18 21:57 UTC, robertengaxway commented on content/en/docs/manage_compliance/_index.md
> +The Amplify API Management Platmform allows you to validate how well your APIs meet the API guidelines of your organization.   This is known as API linting and has been integrated into the Amplify AP
Feon, I changed the wording,  Is that better?

2023-05-18 21:59 UTC, robertengaxway commented on content/en/docs/manage_compliance/_index.md
> +Compliance validation is the verification of your APIs in terms of how thy meeet the guidelines defined in a rule set.  Both an API Design and Security rule set can be applied to all the APIs in a se
fixed

2023-05-18 22:01 UTC, robertengaxway commented on content/en/docs/manage_compliance/_index.md
> +API Compliance Validation can be enabled/disabled per Environment.   Navigate to the Topology screen then create/edit an environment.   The environment wizard with have a **Compliance Profile** step,
fixed

2023-05-18 22:04 UTC, robertengaxway commented on content/en/docs/manage_compliance/_index.md
> +API Compliance Validation can be enabled/disabled per Environment.   Navigate to the Topology screen then create/edit an environment.   The environment wizard with have a **Compliance Profile** step,
fixed

2023-05-18 22:04 UTC, robertengaxway commented on content/en/docs/manage_compliance/_index.md
> +In the Services Registry of the WebUI, there are columns with the Compliance Grading of each API.   Hover over the grading letter to view the counts.
fixed

2023-05-18 22:13 UTC, robertengaxway commented on content/en/docs/manage_compliance/_index.md
> +For example, an API can be checked for compliance in terms of the API methods supported or the presence of a security policy.  The gradiing results of the compliance are measured in the number of Err
fixed

2023-05-18 22:14 UTC, robertengaxway commented on content/en/docs/manage_compliance/_index.md
> +The Amplify API Management Platmform allows you to validate how well your APIs meet the API guidelines of your organization.   This is known as API linting and has been integrated into the Amplify AP
fixed

2023-05-18 22:18 UTC, robertengaxway commented on content/en/docs/manage_compliance/_index.md
> +With the growth of API usage, there is a need for make sure the APIs are technically correct and meet the API standards of your organization.
fixed

2023-05-18 22:24 UTC, feons commented on content/en/docs/manage_compliance/_index.md
> +API Compliance Validation can be enabled/disabled per Environment.   Navigate to the Topology screen then create/edit an environment.   The environment wizard has a **Compliance Profile** step, where
Notice that we use `environment` in certain places and `Environment` in others, wondering if that's intentional?

2023-05-18 22:59 UTC, cbordier approved these changes
All good to me

2023-05-19 00:01 UTC, jquick-axway approved these changes

2023-05-19 23:01 UTC, robertengaxway approved these changes
approved

2023-05-21 20:48 UTC, merged