New - Manage your compliance with Axway
Axway/amplify-central pull request #306
Opened 2023-05-24 21:46 UTC by lbadenhop

Thank you for your contribution to the Amplify-Central repo.

## Describe the changes

Enter a brief description of your changes to communicate to the reviewers what you changed and why.

## Deploy preview link

Please add the deploy preview link to the **specific page** that you've changed.

## Checklist for contributors

Before submitting this PR:

* Verify that all status checks have passed
* For more information on the Markdown linter rules, see [DavidAnson/markdownlint](https://github.com/DavidAnson/markdownlint)
* For first-time contributors, ensure that you have signed the [Axway CLA](https://cla.axway.com/)

2023-05-24 21:48 UTC, docsbuilder commented
### <span aria-hidden="true">✅</span> Deploy preview is ready!

 |  Name | Link |
 |---------------------------------|------------------------|
 |<span aria-hidden="true">🔨</span> Latest commit | 7567c9a |
 |<span aria-hidden="true">😎</span> Deploy preview | http://PR-306.amplify-central.opendocs-builder.pcloud.axway.int |

2023-06-07 19:56 UTC, jquick-axway requested changes

2023-06-07 19:56 UTC, jquick-axway commented on content/en/docs/manage_compliance/compliance_axwaycli.md
> +* Using the Axway Central Central CLI:
It says "Central" twice.

2023-06-07 19:56 UTC, jquick-axway commented on content/en/docs/manage_compliance/compliance_axwaycli.md
> +axway centrea get environment test -o yaml
Typo: "centrea" should be "central"

2023-06-27 19:06 UTC, robertengaxway commented
> @robertengaxway , do you need help in providing example YAML/JSON? I gave you example files a few weeks earlier that should help with this.

Yes please

2023-06-30 21:50 UTC, robertengaxway commented on content/en/docs/manage_compliance/compliance_axwaycli.md
> +
added it

2023-06-30 21:50 UTC, robertengaxway commented on content/en/docs/manage_compliance/compliance_axwaycli.md
> +axway centrea get environment test -o yaml
fixed typo

2023-07-04 01:12 UTC, jquick-axway commented
@lbadenhop, @robertengaxway, I don't have permission to make changes to this branch. So, I made the changes needed in my own forked branch here...
https://github.com/Axway/amplify-central/pull/323

2023-07-05 16:10 UTC, lbadenhop commented
Closing PR. Replaced by https://github.com/Axway/amplify-central/pull/323.

2023-07-05 16:10 UTC, closed without merging