June 30 Release Notes
Axway/amplify-central pull request #320
Opened 2023-06-26 18:19 UTC by lbadenhop

Thank you for your contribution to the Amplify-Central repo.

## Describe the changes

Enter a brief description of your changes to communicate to the reviewers what you changed and why.

## Deploy preview link

Please add the deploy preview link to the **specific page** that you've changed.

## Checklist for contributors

Before submitting this PR:

* Verify that all status checks have passed
* For more information on the Markdown linter rules, see [DavidAnson/markdownlint](https://github.com/DavidAnson/markdownlint)
* For first-time contributors, ensure that you have signed the [Axway CLA](https://cla.axway.com/)

2023-06-26 18:21 UTC, docsbuilder commented
### <span aria-hidden="true">✅</span> Deploy preview is ready!

 |  Name | Link |
 |---------------------------------|------------------------|
 |<span aria-hidden="true">🔨</span> Latest commit | 5e7c97b |
 |<span aria-hidden="true">😎</span> Deploy preview | http://PR-320.amplify-central.opendocs-builder.pcloud.axway.int |

2023-07-02 16:47 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20230630_amplify.md
> +* **Category publication** - Categories owner can publish category only to the Marketplace their team has the publication rights available.
**Category publication** - The owner of a category can make a category visible only in Markeplaces they have publication preferences enabled.

2023-07-02 16:58 UTC, georgiana-caras requested changes

2023-07-02 16:58 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20230630_amplify.md
> +* **Product resources sort** -  A new option is available when publishing a product: display resource in marketplace grouped per asset. Once this option is activated, the product resources will be so
**Display resources grouped by asset**-  A new option **display resource in marketplace grouped per asset** is available when publishing a product. Once this option is activated, the resources that appear in the Resource Table of a product in the Marketplace will be displayed sorted in alphabetical order,  first by the Asset title and then by the resource name.

2023-07-02 16:58 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20230630_amplify.md
> +* **Product plan creation** - A warning icon is present in beside the plan name just after creating a plan. Now, a refresh action has been added and the warning icon is no moe visible.
**Product plan creation** - After creating a plan, a warning icon was displayed by the plan name. With this fix, a refresh action has been introdicced and the warning icon is no longer visible.

2023-07-02 16:58 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20230630_amplify.md
> +* **Product visibility side blade** - The publication status of the marketplace is not always accurate. Now, the status is correctly reflected.
**Product visibility** - The publication status of a product in a Marketplace was at times inaccurate. Now, the status is correctly reflected.

2023-07-02 16:58 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20230630_amplify.md
> +* **Product Category label** - In the product wizard, some extra labels for the Category page have been removed.
**Product Category label** - In the product wizard, some extra labels on the Category page have been removed.

2023-07-02 16:58 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20230630_amplify.md
> +* **Multi-value filtering** - All the filters of the Business Insights screens are accepting multiple values as a criteria. And those criteria are persistent from one screen to another hen relevant.
These filtering criteria are persisted from one screen to another when relevant.

2023-07-02 16:58 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20230630_amplify.md
> +* **Product resources sort** -  A new option is available when publishing a product: display resource in marketplace grouped per asset. Once this option is activated, the product resources will be so
Display resources grouped by asset - A new option display resource in marketplace grouped per asset is available when publishing a product. Once this option is activated, the resources that appear in the Resource Table of a product in the Marketplace will be displayed sorted in alphabetical order, first by the Asset title and then by the resource name.

2023-07-03 14:46 UTC, robertengaxway approved these changes
I approve

2023-07-03 23:29 UTC, merged