July 14 Release Notes
Axway/amplify-central pull request #324
Opened 2023-07-10 21:34 UTC by lbadenhop

Thank you for your contribution to the Amplify-Central repo.

## Describe the changes

Enter a brief description of your changes to communicate to the reviewers what you changed and why.

## Deploy preview link

Please add the deploy preview link to the **specific page** that you've changed.

## Checklist for contributors

Before submitting this PR:

* Verify that all status checks have passed
* For more information on the Markdown linter rules, see [DavidAnson/markdownlint](https://github.com/DavidAnson/markdownlint)
* For first-time contributors, ensure that you have signed the [Axway CLA](https://cla.axway.com/)

2023-07-10 21:36 UTC, docsbuilder commented
### <span aria-hidden="true">✅</span> Deploy preview is ready!

 |  Name | Link |
 |---------------------------------|------------------------|
 |<span aria-hidden="true">🔨</span> Latest commit | 35615a4 |
 |<span aria-hidden="true">😎</span> Deploy preview | http://PR-324.amplify-central.opendocs-builder.pcloud.axway.int |

2023-07-14 18:22 UTC, georgiana-caras requested changes

2023-07-14 18:22 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20230714_amplify.md
> +* None.
There are no new features in this release.

2023-07-14 18:22 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20230714_amplify.md
> +* **Product plan creation does not stay in the Product Plan section** - When a plan is created, the user is now redirected to the Product Plan section to see the result of its creation.
**Product plan creation** - Prior to this fix,  after creating a product plan the user was taken back to the first tab on the product details, instead of the Plans tab. Now the user is directed to the Plans tab to view the plan definition.

2023-07-14 18:22 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20230714_amplify.md
> +* **Impossible to create a plan** - after the user saved his plan, a refresh has been added to enable fetching the correct plan status. Since the treatment of the plan creation could be long, the ref
**Product plan created with wrong status** - Prior to this fix, a wrong status was displayed after the plan creation. A refresh of the screen is now performed automatically to enable fetching the right status after a plan is created. The refresh action is performed 3 times with a delay of 2 seconds between each tentative.

2023-07-14 18:22 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20230714_amplify.md
> +* **The publication of a product fails when including plan in invalid state** - The publication screen has been enriched to prevent the user from activating an invalid plan during the product publica
In addition, when there are no valid plans to activate when publishing a product, the user will see a message with the number of plans already activated.

2023-07-14 18:22 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20230714_amplify.md
> +* **Category deletion popup enrichment** - The delete category confirmation popup is now displaying the list of category that are planned to be deleted.
the list of categories to be deleted

2023-07-14 18:22 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20230714_amplify.md
> +* **Feature** - Description.
There are no new features in this release.

2023-07-14 18:22 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20230714_amplify.md
> +* **Display the actual swagger version of the Service** - The resource version displayed is coming from the the underline service swagger (`info.version`).
**Display the actual swagger version of the API** - The API version as set in the swagger specification ('info.version' ) is now displayed in the resource table of a product.

2023-07-14 23:19 UTC, cbordier approved these changes
I approve the changes

2023-07-14 23:28 UTC, merged