July 28 Release Notes
Axway/amplify-central pull request #328
Opened 2023-07-21 23:12 UTC by lbadenhop

Thank you for your contribution to the Amplify-Central repo.

## Describe the changes

Enter a brief description of your changes to communicate to the reviewers what you changed and why.

## Deploy preview link

Please add the deploy preview link to the **specific page** that you've changed.

## Checklist for contributors

Before submitting this PR:

* Verify that all status checks have passed
* For more information on the Markdown linter rules, see [DavidAnson/markdownlint](https://github.com/DavidAnson/markdownlint)
* For first-time contributors, ensure that you have signed the [Axway CLA](https://cla.axway.com/)

2023-07-21 23:14 UTC, docsbuilder commented
### <span aria-hidden="true">✅</span> Deploy preview is ready!

 |  Name | Link |
 |---------------------------------|------------------------|
 |<span aria-hidden="true">🔨</span> Latest commit | 1acacae |
 |<span aria-hidden="true">😎</span> Deploy preview | http://PR-328.amplify-central.opendocs-builder.pcloud.axway.int |

2023-07-31 16:49 UTC, georgiana-caras requested changes

2023-07-31 16:49 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20230728_amplify.md
> +* **Embedded AWS Traceability Agent** - A new Embedded Agent traceability service for AWS Gateway is now available.  The traceability service reqires an Access Log ARN (Amazon Resource Name) to acces
requires

2023-07-31 16:49 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20230728_amplify.md
> +* **Custom Settings for the Embedded AWS Agent** - The Central WebUI, create/edit Environments page, can be used to set customer settings for either the Discovery or Traceabiliey service.   For examp
custom settings
Traceability

2023-07-31 16:49 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20230728_amplify.md
> +* **Subscriptions and accessRequest filter does not show all the team** - Subscriptions and AccessRequest list now display in the team filter all the teams present in the system to allow providers to
**Subscriptions and accessRequest filters do no show all teams** - The team filter displayed in both the Subscriptions and the Access Requests screens now includes all teams available in the platform.

2023-07-31 16:49 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20230728_amplify.md
> +* **Plan status update** - an automatic refresh is performed once a plan gets deprecated to show correctly its new status to the user.
**Plan status update** - When a plan gets deprecated, the table is automatically refreshed to display the proper plan status.

2023-07-31 16:49 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20230728_amplify.md
> +* **Product visibility screen for private marketplace is missing the consumption preferences** - The missing field are now visible regardless of the marketplace type (public / private).
The missing configuration is now visible regardless of the marketplace type (public / private).

2023-07-31 16:49 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20230728_amplify.md
> +* **Product activation failure after removing product documentation overview** - the remove of product document from the document overview is now cleaning the resource correctly and does not prevent
The removal of a product document from the document overview is no longer preventing the user from creating a new product release.

2023-07-31 16:49 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20230728_amplify.md
> +* **Impossible to archive a deprecated plan when attached to migrated subscription** - The archival of a plan is now possible even if there are some migrated subscriptions attached to it. The plan ar
**Impossible to archive a deprecated plan when attached to migrated subscriptions** - The archival of a plan is now possible even if there are still associated subscriptions in migrated states. The plan archival will force the archive of associated migrated subscriptions. A confirmation popup listing the remaining migrated subscriptions is displayed for the user to confirm the action.

2023-08-01 17:47 UTC, cbordier approved these changes
I approve the changes

2023-08-01 23:20 UTC, merged