October 20 Release Notes
Axway/amplify-central pull request #364
Opened 2023-10-18 19:13 UTC by lbadenhop

Thank you for your contribution to the Amplify-Central repo.

## Describe the changes

Enter a brief description of your changes to communicate to the reviewers what you changed and why.

## Deploy preview link

Please add the deploy preview link to the **specific page** that you've changed.

## Checklist for contributors

Before submitting this PR:

* Verify that all status checks have passed
* For more information on the Markdown linter rules, see [DavidAnson/markdownlint](https://github.com/DavidAnson/markdownlint)
* For first-time contributors, ensure that you have signed the [Axway CLA](https://cla.axway.com/)

2023-10-18 19:15 UTC, docsbuilder commented
### <span aria-hidden="true">âœ…</span> Deploy preview is ready!

 |  Name | Link |
 |---------------------------------|------------------------|
 |<span aria-hidden="true">ðŸ”¨</span> Latest commit | a555211 |
 |<span aria-hidden="true">ðŸ˜Ž</span> Deploy preview | http://PR-364.amplify-central.opendocs-builder.pcloud.axway.int |

2023-10-23 16:53 UTC, georgiana-caras requested changes

2023-10-23 16:53 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20231020_amplify.md
> +* **Migrate Subscription from archived plan** - From Central > Product Foundry > Plan list, it is now possible to access the *Migrate* menu when a plan is already archived to be able to migrate remai
**Migrate subscriptions from a deprecated plan** - Providers can now subscriptions from a plan that is in **deprecated** state. The Migration menu action is disabled when there are no remaining active subscriptions on the plan.

2023-10-23 16:53 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20231020_amplify.md
> +* **Document library allows to create Markdown document** = The Document Library is now capable of creating Markdown document. Those document can be re-use in the Product Documentation or in Marketpl
move this line under feature updates.

2023-10-23 16:53 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20231020_amplify.md
> +* **Access request Subscription selection** - Since it is no more possible to request multiple access to a resource via the same subscription, the subscription dropdown selection has been enhance to
**Access request Subscription selection**   -Since consumers are now allowed to request access to a resource only once with the same subscription, the Request Access form has been enhanced to allow selecting in the subscruption dropdown menu only those subscriptions that do not have an access request associated, The rrest of the subscriptions are shown with a tooltip indicating the number of applications already linked to the resource, plus a link to the applications.

2023-10-23 16:53 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20231020_amplify.md
> +* **Deleted plan still visible in Marketplace** - It is possible that some synchronization between Marketplace and product Foundry failed to be processed which lead to orphan plan in Marketplace. Now
**Deleted plan still visible in Marketplace**  - Orphan plans are no longer shown in the Marketplace for a product.

2023-10-23 16:53 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20231020_amplify.md
> +* **Homepage hero content alignment is wrong** - with the change on the Marketplace theming we also updated the home page hero content alignment (left / center / right) to respect what the user sets.
**Homepage hero content alignment is wrong** - The hero content positioning issue on the home page has been fixed to take the configuration set by the user.

2023-10-23 16:53 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20231020_amplify.md
> +* **Marketplace theming** - The settings for the Marketplace branding are now fully applied to Consumer Insights screens.
**Marketplace apprearance** - The settings for the Marketplace branding are now fully applied to the Consumer Insights screens.

2023-10-23 18:53 UTC, merged