December Release Notes
Axway/amplify-central pull request #374
Opened 2023-12-11 17:45 UTC by lbadenhop

Thank you for your contribution to the Amplify-Central repo.

## Describe the changes

Enter a brief description of your changes to communicate to the reviewers what you changed and why.

## Deploy preview link

Please add the deploy preview link to the **specific page** that you've changed.

## Checklist for contributors

Before submitting this PR:

* Verify that all status checks have passed
* For more information on the Markdown linter rules, see [DavidAnson/markdownlint](https://github.com/DavidAnson/markdownlint)
* For first-time contributors, ensure that you have signed the [Axway CLA](https://cla.axway.com/)

2023-12-11 17:47 UTC, docsbuilder commented
### <span aria-hidden="true">âœ…</span> Deploy preview is ready!

 |  Name | Link |
 |---------------------------------|------------------------|
 |<span aria-hidden="true">ðŸ”¨</span> Latest commit | bbb47a5 |
 |<span aria-hidden="true">ðŸ˜Ž</span> Deploy preview | http://PR-374.amplify-central.opendocs-builder.pcloud.axway.int |

2023-12-18 19:40 UTC, georgiana-caras requested changes

2023-12-18 19:40 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20231215_amplify.md
> +* **Limit the product plan time** - new option is available when creating a paid plan to limit the number or renewal (unlimited by default). Like this is possible for the consumer to subscribe for a
Configure a plan term lenght -  a new option is now available when creating / editing a plan to allow providers to configure how often a subscription to this plan will renew (unlimited by default). When a subscription reaches the term lenght configured on the plan, the subscription will be automatically cancelled.

2023-12-18 19:40 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20231215_amplify.md
> +* **Remove corrupted resources from Active plan** - when an API Service is removed but was used in a product plan, the product plan becomes corrupted. It is now possible when viewing the plan quota t
remove this sentence: when an API Service is removed but was used in a product plan, the product plan becomes corrupted.

2023-12-18 19:40 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20231215_amplify.md
> +* **Remove corrupted resources from Active plan** - when an API Service is removed but was used in a product plan, the product plan becomes corrupted. It is now possible when viewing the plan quota t
using the **in** icon. I assume it wanted to say: bin icon

2023-12-18 19:40 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20231215_amplify.md
> +* **HTTP Basic not available when authorizing** - With the introduction of the new *Authentication* side panel, it is now possible, for any type of credential, to test the API by providing values tha
The **HTTP Basic** auth type has been added to the Authentication side pane.

2023-12-19 00:24 UTC, merged