Marketplace search and filter
Axway/amplify-central pull request #377
Opened 2023-12-14 16:57 UTC by cbordier

Thank you for your contribution to the Amplify-Central repo.

## Describe the changes

Add a new page to describe what consumer can search / filter in Marketplace.

## Deploy preview link

Please add the deploy preview link to the **specific page** that you've changed.

## Checklist for contributors

Before submitting this PR:

* Verify that all status checks have passed
* For more information on the Markdown linter rules, see [DavidAnson/markdownlint](https://github.com/DavidAnson/markdownlint)
* For first-time contributors, ensure that you have signed the [Axway CLA](https://cla.axway.com/)

2023-12-14 16:59 UTC, docsbuilder commented
### <span aria-hidden="true">âœ…</span> Deploy preview is ready!

 |  Name | Link |
 |---------------------------------|------------------------|
 |<span aria-hidden="true">ðŸ”¨</span> Latest commit | ae59cb6 |
 |<span aria-hidden="true">ðŸ˜Ž</span> Deploy preview | http://PR-377.amplify-central.opendocs-builder.pcloud.axway.int |

2023-12-14 17:28 UTC, cbordier commented
@lbadenhop, @georgiana-caras not all featured are deployed yet but you can start review/comment

2023-12-20 17:59 UTC, lbadenhop approved these changes

2023-12-20 18:00 UTC, lbadenhop commented
@cbordier, please check my edits.

2023-12-20 20:45 UTC, cbordier commented
@lbadenhop your edits are good to go.

2023-12-20 21:58 UTC, georgiana-caras requested changes

2023-12-20 21:58 UTC, georgiana-caras commented on content/en/docs/manage_marketplace/consumer_experience/searching.md
> +Learn how you can find content in the Marketplace.
Learn how you can search through content in the Marketplace.

2023-12-20 21:58 UTC, georgiana-caras commented on content/en/docs/manage_marketplace/consumer_experience/searching.md
> +## What is indexed and available for searching
remove this entire paragraph

2023-12-20 21:58 UTC, georgiana-caras commented on content/en/docs/manage_marketplace/consumer_experience/searching.md
> +## Where to search from
Rename to **Search by keyword**

2023-12-20 21:58 UTC, georgiana-caras commented on content/en/docs/manage_marketplace/consumer_experience/searching.md
> +The search is based on a match pattern. This mean that the results will have the portion of entered text anywhere in the fields mentioned in previous section.
Each main page has a search bar that allows to type a keyword and refine the results. 
**Products search** allows you to look for terms in: 

- product title
- product description
- markdown documentation
- product categories
- API specification

From the **Category** page, you can search categories by: 

- title
- description

From the **Applications** page, you can search applications by: 

- Title

From the **Subscriptions** page, you can search subscriptions by: 

- product title
- product description

The search will looks for a partial or complete match with the keyword that is entered in the search bar.

2023-12-20 21:58 UTC, georgiana-caras commented on content/en/docs/manage_marketplace/consumer_experience/searching.md
> +By default, the product search uses what is entered in the search bar to find a match in product title / description / specification content / Documentation (markdown only) / category title assigned
You can use the search bar to find products by keywords with a match in the: 

- product title
- description
- API specification
- Documentation (markdown only)
- categories

2023-12-21 17:09 UTC, merged