Change Amplify Central to Enterprise Marketplace where appropriate
Axway/amplify-central pull request #378
Opened 2024-01-03 20:20 UTC by lbadenhop

Thank you for your contribution to the Amplify-Central repo.

## Describe the changes

Do not change references to CLI or API. This is the first pass and does not include images.

## Deploy preview link

Please add the deploy preview link to the **specific page** that you've changed.

## Checklist for contributors

Before submitting this PR:

* Verify that all status checks have passed
* For more information on the Markdown linter rules, see [DavidAnson/markdownlint](https://github.com/DavidAnson/markdownlint)
* For first-time contributors, ensure that you have signed the [Axway CLA](https://cla.axway.com/)

2024-01-03 20:23 UTC, docsbuilder commented
### <span aria-hidden="true">✅</span> Deploy preview is ready!

 |  Name | Link |
 |---------------------------------|------------------------|
 |<span aria-hidden="true">🔨</span> Latest commit | 0f87ef5 |
 |<span aria-hidden="true">😎</span> Deploy preview | http://PR-378.amplify-central.opendocs-builder.pcloud.axway.int |

2024-01-08 15:52 UTC, cbordier commented on content/en/docs/connect_manage_environ/connect_api_manager/deploy-your-agents-with-amplify-cli.md
> +      "name": "Enterprise Marketplace",
This should not be changed as it is the current agent output.

2024-01-08 15:52 UTC, cbordier commented on content/en/docs/connect_manage_environ/connect_api_manager/deploy-your-agents-with-amplify-cli.md
> +      "name": "Enterprise Marketplace",
This should not be changed as it is the current agent output.

2024-01-08 15:53 UTC, cbordier commented on content/en/docs/connect_manage_environ/connect_api_manager/gateway-administation.md
> +# central connectivity
Can you put back Amplify?

2024-01-08 15:54 UTC, cbordier commented on content/en/docs/connect_manage_environ/connect_api_manager/gateway-administation.md
> +#### Customizing Discovery Central connectivity variables
Discovery Agent Amplify connectivity variables

2024-01-08 15:54 UTC, cbordier commented on content/en/docs/connect_manage_environ/connect_api_manager/gateway-administation.md
> +      "name"="Enterprise Marketplace",
This should not be changed as it is the current agent output.

2024-01-08 15:55 UTC, cbordier commented on content/en/docs/connect_manage_environ/connect_api_manager/gateway-administation.md
> +# central connectivity
I would prefer to keep Amplify

2024-01-08 20:43 UTC, robertengaxway commented on content/en/docs/connect_manage_environ/connect_api_manager/agent-variables.md
> +| CENTRAL_AGENTNAME                                                  | The agent name of this agent on Enterprise Marketplace.
I would recommend using "Enterprise Marketplace Web UI" here

2024-01-08 20:52 UTC, robertengaxway commented on content/en/docs/connect_manage_environ/connect_api_manager/gateway-administation.md
> +# central connectivity
Or use "Amplify Enterprise Marketplace" here ?

2024-01-08 20:59 UTC, robertengaxway commented on content/en/docs/connect_manage_environ/connect_api_manager/gateway-administation.md
> +# central connectivity
I would recommend using "Amplify Enterprise Marketplace" here

2024-01-08 21:04 UTC, robertengaxway commented on content/en/docs/connect_manage_environ/connect_aws_gateway/cloud-administration-operation.md
> +| Why can’t my agents connect to Amplify?               | Go to **Enterprise Marketplace WebUI > Access > Service Accounts** and make sure that the Service Account is correctly named and valid. Make
I would recommend using "Amplify Enterprise Marketplace Web UI" here

2024-01-08 21:06 UTC, robertengaxway commented on content/en/docs/connect_manage_environ/connect_aws_gateway/deploy-your-agents-1.md
> +# Central connectivity
I would recommend using "Amplify Enterprise Marketplace connectivity" here

2024-01-08 21:07 UTC, robertengaxway commented on content/en/docs/connect_manage_environ/connect_aws_gateway/deploy-your-agents-1.md
> +# Central connectivity
I would recommend using "Amplify Enterprise Marketplace" here

2024-01-08 21:16 UTC, robertengaxway commented on content/en/docs/manage_product_foundry/foundry_support_contact.md
> +The product support contact is saved and assigned to all selected products. Consumers can view the support contact information on the right of the product details screen in the Marketplace UI.
I would recommend using "Enterprise Marketplace Web UI" here

2024-01-08 21:18 UTC, robertengaxway commented on content/en/docs/saas_api_gateway/backend_TLS.md
> +* Use the Enterprise Marketplace WebUI to to confirm TLS is negotiated for your API
I suggest we be consistent with either "Web UI" or "WebUI"

2024-01-08 21:20 UTC, robertengaxway approved these changes
I suggest we use "Enterprise Marketplace Web UI" in general for the UI references and "Enterprise Marketplace" when not referring to the UI

2024-01-16 23:15 UTC, georgiana-caras requested changes

2024-01-16 23:15 UTC, georgiana-caras commented on content/en/docs/integrate_with_central/webhook/_index.md
> -    "product": "AmplifyCentral",
Not sure we should update this property, as it will be impacting the CLI command. @robertengaxway , can you please confirm?

2024-01-16 23:15 UTC, georgiana-caras commented on content/en/docs/integrate_with_central/webhook/api_discovery_webhook.md
> -   "product": "AmplifyCentral",
Not sure we should update this property, as it will be impacting the CLI command. @robertengaxway , can you please confirm?

2024-01-16 23:15 UTC, georgiana-caras commented on content/en/docs/integrate_with_central/webhook/marketplace_subscription_webhook.md
> -  "product": "AmplifyCentral",
Not sure we should update this property, as it will be impacting the CLI command. @robertengaxway , can you please confirm?

2024-01-16 23:15 UTC, georgiana-caras commented on static/samples/central/subscriptionEventPayload.json
> -    "product": "AmplifyCentral",
Not sure we should update this property, as it will be impacting the CLI command. @robertengaxway , can you please confirm?

2024-01-17 21:21 UTC, robertengaxway commented on content/en/docs/connect_manage_environ/connect_apigee_x/_index.md
> +* Given that a specification file is found, the agent then creates an API service, revision, and instance to represent that proxy in Enterprise Marketplace. The agent does not validate or configure a
reworded

2024-01-17 21:26 UTC, robertengaxway commented on content/en/docs/connect_manage_environ/connect_aws_gateway/deploy-your-agents-1.md
> +| **Enterprise Marketplace variables**                  |
I am okay with changing it to "Amplify Variables" but these are mostly variable for the agent to connect to the "Amplify Enterprise Marketplace"

2024-01-17 21:27 UTC, robertengaxway commented on content/en/docs/connect_manage_environ/connect_aws_gateway/deploy-your-agents-with-amplify-cli.md
> +   * **Service account**: can be an existing service account (from platform or Enterprise Marketplace). The installation procedure creates only an Enterprise Marketplace service account. If you choos
sounds good to me

2024-01-17 21:27 UTC, robertengaxway commented on content/en/docs/connect_manage_environ/connect_aws_gateway/embedded-aws-agent-setup.md
> +This CloudWatch Log Group will be used by both agents. Upon discovery of a Rest API stage, the Discovery Agent configures the logging to send details to CloudWatch. The Traceability Agent then watche
ok by me

2024-01-17 21:29 UTC, robertengaxway commented on content/en/docs/connect_manage_environ/connect_azure_gateway/agent-variables.md
> +| **Enterprise Marketplace variables**        |
As long as its the same title as the prior "Variable" comment, I am okay with it

2024-01-17 21:29 UTC, robertengaxway commented on content/en/docs/connect_manage_environ/connect_azure_gateway/deploy-your-agents-with-amplify-cli.md
> +   * **Service account**: can be an existing service account (from platform or Enterprise Marketplace). The installation procedure creates only a Enterprise Marketplace service account. If you choose
okay

2024-01-17 21:33 UTC, robertengaxway commented on content/en/docs/integrate_with_central/webhook/_index.md
> -    "product": "AmplifyCentral",
This is just the title of the product.  It can be changed to whatever name we want use for the product.  I checked with Deepak.

2024-01-17 21:48 UTC, robertengaxway commented on content/en/docs/integrate_with_central/webhook/api_discovery_webhook.md
> -   "product": "AmplifyCentral",
This is just the title of the product. It can be changed to whatever name we want use for the product. I checked with Deepak.

2024-01-17 21:48 UTC, robertengaxway commented on content/en/docs/integrate_with_central/webhook/marketplace_subscription_webhook.md
> -  "product": "AmplifyCentral",
This is just the title of the product. It can be changed to whatever name we want use for the product. I checked with Deepak.

2024-01-17 21:48 UTC, robertengaxway commented on static/samples/central/subscriptionEventPayload.json
> -    "product": "AmplifyCentral",
This is just the title of the product. It can be changed to whatever name we want use for the product. I checked with Deepak.

2024-01-17 22:16 UTC, merged