January 12 Release Notes
Axway/amplify-central pull request #384
Opened 2024-01-08 21:41 UTC by lbadenhop

Thank you for your contribution to the Amplify-Central repo.

## Describe the changes

Enter a brief description of your changes to communicate to the reviewers what you changed and why.

## Deploy preview link

Please add the deploy preview link to the **specific page** that you've changed.

## Checklist for contributors

Before submitting this PR:

* Verify that all status checks have passed
* For more information on the Markdown linter rules, see [DavidAnson/markdownlint](https://github.com/DavidAnson/markdownlint)
* For first-time contributors, ensure that you have signed the [Axway CLA](https://cla.axway.com/)

2024-01-08 21:43 UTC, docsbuilder commented
### <span aria-hidden="true">✅</span> Deploy preview is ready!

 |  Name | Link |
 |---------------------------------|------------------------|
 |<span aria-hidden="true">🔨</span> Latest commit | 46afcc5 |
 |<span aria-hidden="true">😎</span> Deploy preview | http://PR-384.amplify-central.opendocs-builder.pcloud.axway.int |

2024-01-12 22:55 UTC, robertengaxway approved these changes
I approve

2024-01-16 16:03 UTC, georgiana-caras requested changes

2024-01-16 16:03 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20240112_amplify.md
> +* **new created application credentials option** - It is now possible, when asking fdor credentials, to reuse an existing application that already have access to the resource.
Typos and grammar

2024-01-16 16:03 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20240112_amplify.md
> +* **Product resources search fails** - the resource search from the product resource list allows to search either a resource name or a resource groupd name.
**Product resource search** - the search bar on the product resource screen has been fixed to allow searching either by the resource title or the resource group title.

2024-01-16 22:08 UTC, cbordier approved these changes
I approve the changes

2024-01-16 22:13 UTC, merged