January 26 Release Notes
Axway/amplify-central pull request #389
Opened 2024-01-19 20:58 UTC by lbadenhop

Thank you for your contribution to the Amplify-Central repo.

## Describe the changes

Enter a brief description of your changes to communicate to the reviewers what you changed and why.

## Deploy preview link

Please add the deploy preview link to the **specific page** that you've changed.

## Checklist for contributors

Before submitting this PR:

* Verify that all status checks have passed
* For more information on the Markdown linter rules, see [DavidAnson/markdownlint](https://github.com/DavidAnson/markdownlint)
* For first-time contributors, ensure that you have signed the [Axway CLA](https://cla.axway.com/)

2024-01-19 21:02 UTC, docsbuilder commented
### <span aria-hidden="true">✅</span> Deploy preview is ready!

 |  Name | Link |
 |---------------------------------|------------------------|
 |<span aria-hidden="true">🔨</span> Latest commit | c96d13d |
 |<span aria-hidden="true">😎</span> Deploy preview | http://PR-389.amplify-central.opendocs-builder.pcloud.axway.int |

2024-01-29 20:29 UTC, robertengaxway approved these changes
approved

2024-01-29 23:27 UTC, georgiana-caras requested changes

2024-01-29 23:27 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20240126_amplify.md
> +* **Metric Event Improvement** - The Event ID generation has been modified to improve the counting of usage and traffic metrics.
can we provide a little more details here? How is the event id generation leading to improved usage of the traffic?

2024-01-29 23:27 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20240126_amplify.md
> +* **Agent communication Improvement** - The gRPC method of communication between the Agent and the Enterprise Marketplace has been improved,
This seems incomplete

2024-01-29 23:27 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20240126_amplify.md
> +* **Log file directory improvement** - Wildcard usage in directory names have been added for the log file directory.
what are the wildcard used for ?

2024-01-29 23:27 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20240126_amplify.md
> +* **Branch filter configuration** - The GitHub Discovery agent can be configured with a branch filter for the GitHub agent.
What does that result into? APIs discovered in a branch?

2024-01-29 23:27 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20240126_amplify.md
> +* **HSTS Max age too low** - HSTS max age has been increased to 12 months.
what is HSTS? I assume  HTTP Strict Transport Security. How was this affecting customers?

2024-01-29 23:27 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20240126_amplify.md
> +* **Not all swagger endpoints are visible in the methods section** - On product method screen, the Server dropdown shows now all the endpoints available.
There is no product method screen. WE need to rephrase this

2024-01-29 23:27 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20240126_amplify.md
> +* **Access request not visible** - When navigating the multiple product version, as soon as an access request has been created, it is visible regardless of the selected version.
Can we rephase to: We have fixed an issue where the access request button was not visible when browing through old versions of a product.

2024-01-29 23:27 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20240126_amplify.md
> +* **Number of products displayed doesn't match the displayed products** - When a product is in error (i.e., when all its resources are corrupted), the product count from the Browse product page was w
Product count does not march the displayed products

2024-01-29 23:53 UTC, robertengaxway commented on content/en/docs/amplify_relnotes/20240126_amplify.md
> +* **Agent communication Improvement** - The gRPC method of communication between the Agent and the Enterprise Marketplace has been improved,
ok I will add a little more detail but here is the defect description.
"On initial investigation it was identified that the watch controller was closing the gRPC connection due to expired token. In normal scenario the token refreshes are sent from client which was not being sent(to be investigated). The watch controller also monitors the expiration of the token for the stream and on expiry(in case the token refresh is not received) the server closes the gRPC connection. With this the gRPC watch client in agent goes in a bad state and agent keeps sending the subscription request. "

2024-01-30 00:00 UTC, robertengaxway commented on content/en/docs/amplify_relnotes/20240126_amplify.md
> +* **Metric Event Improvement** - The Event ID generation has been modified to improve the counting of usage and traffic metrics.
added a little more detail

2024-01-30 00:11 UTC, robertengaxway commented on content/en/docs/amplify_relnotes/20240126_amplify.md
> +* **Log file directory improvement** - Wildcard usage in directory names have been added for the log file directory.
The wildcard string allows the TA access of multiple filenames which start with EVENT_LOG_PATHS=/test/events/events-traffic/app-temp*/

2024-01-30 00:12 UTC, robertengaxway commented on content/en/docs/amplify_relnotes/20240126_amplify.md
> +* **Branch filter configuration** - The GitHub Discovery agent can be configured with a branch filter for the GitHub agent.
It allows the provider to specify mulltiple branches in the Github repo to be searched for API specs

2024-01-30 13:32 UTC, cbordier commented on content/en/docs/amplify_relnotes/20240126_amplify.md
> +* **HSTS Max age too low** - HSTS max age has been increased to 12 months.
It does not affect customer but Nuclea asked for it.

2024-01-30 13:35 UTC, cbordier commented on content/en/docs/amplify_relnotes/20240126_amplify.md
> +* **Not all swagger endpoints are visible in the methods section** - On product method screen, the Server dropdown shows now all the endpoints available.
We are speaking of this screen here:
![image](https://github.com/Axway/amplify-central/assets/16959488/dee26167-2c6a-4e48-a4f7-4a72b808b493)

2024-01-30 13:40 UTC, cbordier commented on content/en/docs/amplify_relnotes/20240126_amplify.md
> +* **Access request not visible** - When navigating the multiple product version, as soon as an access request has been created, it is visible regardless of the selected version.
updated

2024-01-30 13:40 UTC, cbordier commented on content/en/docs/amplify_relnotes/20240126_amplify.md
> +* **Number of products displayed doesn't match the displayed products** - When a product is in error (i.e., when all its resources are corrupted), the product count from the Browse product page was w
updated

2024-01-30 16:34 UTC, georgiana-caras requested changes

2024-01-30 16:34 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20240126_amplify.md
> +* **API Service version list** - The performance of the API Service Details WebUI has been improved to display a maximum of the first 24 API Service versions.  As you scroll down past the first 24 AP
Let's rename to **Pagination for API Service versions**

2024-01-30 16:34 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20240126_amplify.md
> +**Asset Linked API Service display** - A fix was made to display the all the linked API Resources to an Asset correctly.
**Asset not showing all linked API resources** - A fix was released to show all API resources included in an asset.

2024-01-30 16:34 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20240126_amplify.md
> +* **Resource version not visible when creating a product plan** - The description of the resource available in the plan quota has been enriched with the following pattern: {AssetTile}/{resourceTitle}
@lbadenhop , fix is not yet available in prod. We wil include this in Sprint 3 release notes

2024-01-30 16:34 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20240126_amplify.md
> +* **Line break issue in description fields** - the carriage return is now correctly displayed in Asset and Product description field.
A fix was delievered to properly handle line breaks in the Asset and Product description fields.

2024-01-30 22:27 UTC, merged