February 9 Release Notes
Axway/amplify-central pull request #401
Opened 2024-02-09 15:13 UTC by lbadenhop

Thank you for your contribution to the Amplify-Central repo.

## Describe the changes

Enter a brief description of your changes to communicate to the reviewers what you changed and why.

## Deploy preview link

Please add the deploy preview link to the **specific page** that you've changed.

## Checklist for contributors

Before submitting this PR:

* Verify that all status checks have passed
* For more information on the Markdown linter rules, see [DavidAnson/markdownlint](https://github.com/DavidAnson/markdownlint)
* For first-time contributors, ensure that you have signed the [Axway CLA](https://cla.axway.com/)

2024-02-09 15:15 UTC, docsbuilder commented
### <span aria-hidden="true">✅</span> Deploy preview is ready!

 |  Name | Link |
 |---------------------------------|------------------------|
 |<span aria-hidden="true">🔨</span> Latest commit | ef231a9 |
 |<span aria-hidden="true">😎</span> Deploy preview | http://PR-401.amplify-central.opendocs-builder.pcloud.axway.int |

2024-02-09 21:43 UTC, robertengaxway approved these changes

2024-02-12 21:46 UTC, lbadenhop commented
Spell checked. Will review/edit once @georgiana-caras  approves content.

2024-02-12 22:00 UTC, georgiana-caras requested changes

2024-02-12 22:00 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20240209_amplify.md
> +* **Line break issue in description fields** - Editing a product description allow to enter line break. Those breaks are correctly render after saving the product.
**Line break issue in description fields** - The product description can now handle line breaks.

2024-02-12 22:00 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20240209_amplify.md
> +* **Log audit concern** - When Axway is upgrading the model and that update triggers event that are displayed in the event logs, those events are now identified as belonging to **Axway Internal Admin
**System initiated events logged with a platform user account** - All actions initiated by the system such as upgrade  / migration codes are now now reported in the Activity events as being performed by "Axway Internal Admin" user.

2024-02-12 22:00 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20240209_amplify.md
> +* **Cannot delete a stage** - After removing a stage to an environment, it was not possible to remove the stage because of some remaining reference in the environment. An upgrade procedure has been r
**Impossible to delete a stage** - We have fixed an issue where it was not possible to remove a stage, even after it was no longer in use. This was caused by some remaining references on the environments that were still pointing to the stage. An upgrade procedure has been run to clean up all the invalid references. This upgrade will trigger a stage update event in the Activity log that is now reported as performed by the Axway Internal Admin user.

2024-02-12 23:58 UTC, cbordier approved these changes
Looks good

2024-02-13 17:35 UTC, merged