February 23 Release Notes
Axway/amplify-central pull request #402
Opened 2024-02-14 21:29 UTC by lbadenhop

Thank you for your contribution to the Amplify-Central repo.

## Describe the changes

Enter a brief description of your changes to communicate to the reviewers what you changed and why.

## Deploy preview link

Please add the deploy preview link to the **specific page** that you've changed.

## Checklist for contributors

Before submitting this PR:

* Verify that all status checks have passed
* For more information on the Markdown linter rules, see [DavidAnson/markdownlint](https://github.com/DavidAnson/markdownlint)
* For first-time contributors, ensure that you have signed the [Axway CLA](https://cla.axway.com/)

2024-02-14 21:30 UTC, docsbuilder commented
### <span aria-hidden="true">✅</span> Deploy preview is ready!

 |  Name | Link |
 |---------------------------------|------------------------|
 |<span aria-hidden="true">🔨</span> Latest commit | 9172282 |
 |<span aria-hidden="true">😎</span> Deploy preview | http://PR-402.amplify-central.opendocs-builder.pcloud.axway.int |

2024-02-23 22:43 UTC, vivekschauhan commented on content/en/docs/amplify_relnotes/20240223_amplify.md
> +| GitLab                                     | 1.0.1                    |
1.0.2

2024-02-23 22:47 UTC, vivekschauhan commented on content/en/docs/amplify_relnotes/20240223_amplify.md
> +* **Seccrity Methods specification** - The SDK has been updated to enable the Agent to configure security.  This is used to enable the Try-it capability for Kong Gateway.
Seccrity -> Security

2024-02-23 22:47 UTC, vivekschauhan commented on content/en/docs/amplify_relnotes/20240223_amplify.md
> +* **Traceability Agent Usage Reporting** - The usage reporting file contains a granularity interval which indicates the reporting period.   This was fixed to report the correct granularity instead of
alway -> always

2024-02-23 22:49 UTC, vivekschauhan commented on content/en/docs/amplify_relnotes/20240223_amplify.md
> +#### Mulesoft Gateway Agent
"Kong Agent" I guess

2024-02-23 22:52 UTC, vivekschauhan commented on content/en/docs/amplify_relnotes/20240223_amplify.md
> +The latest version of the [Axway Central CLI is v2.25.0 on NPM](https://www.npmjs.com/package/@axway/axway-central-cli/v/2.25.0). There are no new enhancements or bug fixes for Axway Central CLI in t
Should we change this "There are no new enhancements or bug fixes for Axway Central CLI in this release" as there are new feature update and bug fix

2024-02-23 22:54 UTC, vivekschauhan commented on content/en/docs/amplify_relnotes/_index.md
> +* **GitLab** - 1.0.1
Version seems to be from previous release and Kafka is missing

2024-02-23 22:59 UTC, robertengaxway commented on content/en/docs/amplify_relnotes/20240223_amplify.md
> +| GitLab                                     | 1.0.1                    |
Ah Gitlab is 1.0.2 , Dale started that one late :)

2024-02-23 23:00 UTC, robertengaxway commented on content/en/docs/amplify_relnotes/20240223_amplify.md
> +* **Traceability Agent Usage Reporting** - The usage reporting file contains a granularity interval which indicates the reporting period.   This was fixed to report the correct granularity instead of
fixed

2024-02-23 23:03 UTC, robertengaxway commented on content/en/docs/amplify_relnotes/20240223_amplify.md
> +##### Enhancements for Kong Gateway Agent
I removed the mulesoft enhancement because it was really for Kong (the security setting)

2024-02-23 23:09 UTC, vivekschauhan approved these changes

2024-02-26 17:28 UTC, cbordier commented on content/en/docs/amplify_relnotes/20240223_amplify.md
> +
Maybe we could indicate there that now agents are visible from any organization:
- from Help menus > Downloads > Repository and then search for agents.
OR 
- from the following url: https://repository.axway.com/catalog?q=agents

2024-02-26 21:41 UTC, georgiana-caras requested changes

2024-02-26 21:41 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20240223_amplify.md
> +
I like this suggestion.

2024-02-26 21:41 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20240223_amplify.md
> +* **Customize the product versioning** - When releasing a product, it is now possible to add your own custom product version, a short description as well as to automatically archive previous version.
New settings have been added to the Release Product version screen to allow providers to add a custom product version. The display of the custom product version in a Marketplace can be controlled through a setting on the [Marketplace Settings screen](/docs/manage_marketplace/customize_marketplace/marketplace_settings#configure-settings). In addition to providing a custom product version, the user can choose to archive older version and add a short description to indicate what is included in the new version. [Refer to activate a product release - step 7](/docs/manage_product_foundry/foundry_product_management#actiovate-a-product-release) for more details.

2024-02-26 21:41 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20240223_amplify.md
> +* **Product Ratings** - Provider can turn on the Rating feature for a specific Marketplace. Refer to [Marketplace settings - Ratings](/docs/manage_marketaplace/customize_marketplace/marketplace_ratin
Remove this section.

2024-02-26 21:41 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20240223_amplify.md
> +* **Custom product version** - Based on provider preferences, the generated product version could be replaced by a custom version. Provider can also decide to limit the product history to only the la
Remove the custom product version. It is enough to mention it under Product Foundry

2024-02-26 21:41 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20240223_amplify.md
> +* **Product rating** - When enabled by the provider, consumer can rate the product they have access to. Refer to [Rate a product](/docs/manage_marketplace/consumer_experience/ratings_reviews)
**Product ratings** - Consumers can now rate their statisfaction with a product in the Marketplace. Marketplace Managers must turn on the Product Ratings feature in order for Consumer to be able to rate a product. Refer to [Marketplace settings - Ratings](/docs/manage_marketaplace/customize_marketplace/marketplace_ratings_reviews). Product owners can see the submitted ratings from the product details screen, in the Product Foundry.

2024-02-26 21:41 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20240223_amplify.md
> +* **Product release not present in Marketplace even if product is published and release is active** - A race condition when releasing a product version has been corrected to be able to see all the pr
**Active product version not visible in a Marketplace for published products - An issue has been fixed to display all active product versions in a Marketplace.

2024-02-26 21:41 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20240223_amplify.md
> +* **Product details not visible in small screen resolution** - The product details screen is now responsive to the screen size.
**Product details not visible on small screens** - Users can now see the product details when they browse the product from screens with small resolution.

2024-02-26 23:42 UTC, cbordier approved these changes
I approve.

2024-02-26 23:48 UTC, merged