March 8 Release Notes
Axway/amplify-central pull request #417
Opened 2024-03-06 22:34 UTC by lbadenhop

Thank you for your contribution to the Amplify-Central repo.

## Describe the changes

Enter a brief description of your changes to communicate to the reviewers what you changed and why.

## Deploy preview link

Please add the deploy preview link to the **specific page** that you've changed.

## Checklist for contributors

Before submitting this PR:

* Verify that all status checks have passed
* For more information on the Markdown linter rules, see [DavidAnson/markdownlint](https://github.com/DavidAnson/markdownlint)
* For first-time contributors, ensure that you have signed the [Axway CLA](https://cla.axway.com/)

2024-03-06 22:36 UTC, docsbuilder commented
### <span aria-hidden="true">✅</span> Deploy preview is ready!

 |  Name | Link |
 |---------------------------------|------------------------|
 |<span aria-hidden="true">🔨</span> Latest commit | b063e8c |
 |<span aria-hidden="true">😎</span> Deploy preview | http://PR-417.amplify-central.opendocs-builder.pcloud.axway.int |

2024-03-12 18:23 UTC, georgiana-caras requested changes

2024-03-12 18:23 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20240308_amplify.md
> +* **Clean variable settings** - Support for enable the settomg of the INPUTS_CLEAN_REMOVED and INPUTS_CLOSE_REMOVED variables to TRUE or FALSE has been added.  In addtion, support has been added for
fix typos

2024-03-12 18:23 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20240308_amplify.md
> +* **Invoke Policy** - Fixed an issue with a NULL pointer exception when discovering an API with Invoke Policy.
with invoke policy as the inbound security profile.

2024-03-12 18:23 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20240308_amplify.md
> +* **Discovery from a local file** - The Apigee Edge discovery agent has added support to read API Specifications from the local file system.
can we add few more lines to explain hhow the api specs are discovered? based on tags, etc

2024-03-12 18:23 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20240308_amplify.md
> +* **Discovery of APIs with no specification - The Apigee Edge Discovery Agent can be configure to discovery APIs with no associated API specification file.  The variable to enable this is APIGEE_SPEC
In order to enable it, the variable APIGEE_SPECCONFIG_UNSTRUCTURED must be set to TRUE.

2024-03-12 22:56 UTC, georgiana-caras approved these changes

2024-03-13 02:04 UTC, merged