March 22 Release Notes
Axway/amplify-central pull request #421
Opened 2024-03-18 18:56 UTC by lbadenhop

Thank you for your contribution to the Amplify-Central repo.

## Describe the changes

Enter a brief description of your changes to communicate to the reviewers what you changed and why.

## Deploy preview link

Please add the deploy preview link to the **specific page** that you've changed.

## Checklist for contributors

Before submitting this PR:

* Verify that all status checks have passed
* For more information on the Markdown linter rules, see [DavidAnson/markdownlint](https://github.com/DavidAnson/markdownlint)
* For first-time contributors, ensure that you have signed the [Axway CLA](https://cla.axway.com/)

2024-03-18 18:58 UTC, docsbuilder commented
### <span aria-hidden="true">✅</span> Deploy preview is ready!

 |  Name | Link |
 |---------------------------------|------------------------|
 |<span aria-hidden="true">🔨</span> Latest commit | d6ea5f5 |
 |<span aria-hidden="true">😎</span> Deploy preview | http://PR-421.amplify-central.opendocs-builder.pcloud.axway.int |

2024-03-25 21:47 UTC, georgiana-caras requested changes

2024-03-25 21:47 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20240322_amplify.md
> +View agents from any organization:
Access the list of available agents from your organization.

2024-03-25 21:47 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20240322_amplify.md
> +* **Security Patches** - The Agent SDK was enhanced to include some security patchesn.
typo

2024-03-25 21:47 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20240322_amplify.md
> +* **Embedded Apigee X OAuth Discovery** - A fix was made to discover and create the Asset Request Definition for an API using an OAuth Security Scheme.
A fix was made to discover the APIs that are using an OAuth Security Scheme. This results in Marketplace users being able to request access and generate an OAuth credential.

2024-03-25 21:47 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20240322_amplify.md
> +* **Document library document** - it is now possible to Edit any document from the Document Library by using the ellipsis menu `Edit` or using the Edit button on the Document details screen. The docu
You can only change the content, but not allowed to change the document type.

2024-03-26 04:08 UTC, georgiana-caras approved these changes

2024-03-26 13:29 UTC, cbordier commented on content/en/docs/amplify_relnotes/20240322_amplify.md
> +View agents from any organization:
Integrated.

2024-03-26 13:39 UTC, cbordier approved these changes
I approve

2024-03-26 14:52 UTC, merged