APIGOV-27622 New "Manage your runtime security" section
Axway/amplify-central pull request #426
Opened 2024-04-01 20:51 UTC by lbadenhop

Thank you for your contribution to the Amplify-Central repo.

## Describe the changes

Enter a brief description of your changes to communicate to the reviewers what you changed and why.

## Deploy preview link

Please add the deploy preview link to the **specific page** that you've changed.

## Checklist for contributors

Before submitting this PR:

* Verify that all status checks have passed
* For more information on the Markdown linter rules, see [DavidAnson/markdownlint](https://github.com/DavidAnson/markdownlint)
* For first-time contributors, ensure that you have signed the [Axway CLA](https://cla.axway.com/)

2024-04-01 20:54 UTC, docsbuilder commented
### <span aria-hidden="true">✅</span> Deploy preview is ready!

 |  Name | Link |
 |---------------------------------|------------------------|
 |<span aria-hidden="true">🔨</span> Latest commit | f58fef7 |
 |<span aria-hidden="true">😎</span> Deploy preview | http://PR-426.amplify-central.opendocs-builder.pcloud.axway.int |

2024-04-02 16:34 UTC, lbadenhop commented on content/en/docs/runtime_security/_index.md
> +With an increasing number of APIs, API providers and consumers of APIs, there is a pressing need to capture API traffic and scan the API traffic to assess the security threat(s).
```suggestion
With an increasing number of APIs, API providers and consumers of APIs, there is a pressing need to capture and scan API traffic to assess security threats.
```

2024-04-02 16:35 UTC, lbadenhop commented on content/en/docs/runtime_security/_index.md
> +The Amplify API Management platform allows you to assess the runtime compliance of your APIs from a secruity threat perspective. This is known as API Runtime Compliance and has been integrated into t
```suggestion
Amplify's Runtime Compliance entitlement for the API Management platform  allows you to assess the runtime compliance of your APIs from a security threat perspective. 
```

2024-04-02 16:55 UTC, lbadenhop commented on content/en/docs/runtime_security/_index.md
> +To get started, you have to create an Amplify environment which connects to Graylog API Security and to retrieve the security results.   The Graylog API Security data is correlated with the Managed A
```suggestion
To get started, must create an Amplify environment that connects to Graylog API Security and to retrieve the security results.   The Graylog API Security retrieves the security results and correlates the data with the Managed APIs from the API Gateways connected to the Amplify Enterprise Marketplace to determine a security grading.  

{{< alert title="Note" color="primary" >}} APIs that do not match the API Gateways in the Amplify Enterprise Marketplace are represented as Runtime Unmanaged APIs with a security grading.  These unmanaged runtime APIs are unknown APIs not registered with an API Gateway. See (link) for security grading details.{{< /alert >}} 
```

2024-04-02 16:55 UTC, lbadenhop commented on content/en/docs/runtime_security/_index.md
> +Runtime compliance is assessment of the potential security risk based on the real API traffic.  Amplify has integrated with Graylog API Security to monitor and assess the security threats from real c
```suggestion
Runtime compliance is the assessment of potential security risks based on real-time API traffic.  Amplify has integrated with Graylog API Security to monitor and assess API traffic for security threats.  For example, the captured API traffic is scanned by Graylog API security to detect real attacks, leaks, and other threats.
```

2024-05-03 18:45 UTC, robertengaxway approved these changes

2024-05-03 20:54 UTC, georgiana-caras requested changes

2024-05-03 20:54 UTC, georgiana-caras commented on content/en/docs/runtime_security/_index.md
> +Amplify's runtime compliance entitlement for the API Management platform allows you to assess the runtime compliance of your APIs from a security threat perspective. Runtime Compliance is an entitlem
instead of entitlement i would say "feature" and remove this "for the API Management platform"

2024-05-03 20:54 UTC, georgiana-caras commented on content/en/docs/runtime_security/_index.md
> +Amplify's runtime compliance entitlement for the API Management platform allows you to assess the runtime compliance of your APIs from a security threat perspective. Runtime Compliance is an entitlem
Runtime Compliance is an entitlement you can purchase from Axway as part of the API Management platform. 
I would replace this with: Contact Axway Support at support.axway.com or reach out to your Axway representative to learn how to enable the Runtime Compliance for your organization.

2024-05-03 22:09 UTC, robertengaxway commented on content/en/docs/runtime_security/_index.md
> +Amplify's runtime compliance entitlement for the API Management platform allows you to assess the runtime compliance of your APIs from a security threat perspective. Runtime Compliance is an entitlem
Edited based on your feedback

2024-05-03 23:03 UTC, merged