April 19 Release Notes
Axway/amplify-central pull request #436
Opened 2024-04-16 18:24 UTC by lbadenhop

Thank you for your contribution to the Amplify-Central repo.

## Describe the changes

Enter a brief description of your changes to communicate to the reviewers what you changed and why.

## Deploy preview link

Please add the deploy preview link to the **specific page** that you've changed.

## Checklist for contributors

Before submitting this PR:

* Verify that all status checks have passed
* For more information on the Markdown linter rules, see [DavidAnson/markdownlint](https://github.com/DavidAnson/markdownlint)
* For first-time contributors, ensure that you have signed the [Axway CLA](https://cla.axway.com/)

2024-04-22 21:18 UTC, georgiana-caras requested changes

2024-04-22 21:18 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20240419_amplify.md
> +* **Resource count when assigning an asset to a product is removed** - The asset resource count depends on the asset version that is assigned to a product version. Until we now which version is used,
**Enhancement to assigning an asset to a product** - The resource number is no longer included in the table view displayed on the screen for linking an asset to a product. The asset resource count is calculated based on the asset version. Since we cannot accurately calculate the count until the user selects a version for the asset, we decided to remove the resource count it from the table.

2024-04-22 21:18 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20240419_amplify.md
> +* **Advanced search result page** - The search from the Home page or the Advanced search from the browse product page are now redirecting the user to a specific page where they can see where this sea
**Search results display** - An enhancement has been added to the Marketplace search to show the results in an organized and meanigful way. Refer to [Advanced Search result documentation](/docs/manage_marketplace/consumer_experience/searching#advanced-search-result-page)

2024-04-22 21:18 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20240419_amplify.md
> +* **Custom billing integration** - A new Vendor option is available regarding the billing integration. This option enable you integrate with any billing system you have in case our native integration
@lbadenhop, can you please fix the typos. Thank you.

2024-04-22 21:18 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20240419_amplify.md
> +* **UI - Product release type unknown if there are over 20 releases** - In case you have more than 20 product release, some product release information were missing because of the paginated query. No
**Unknown product release type** - The product release type could not be displayed for products with more than 20 product versions, due to a pagination query issue. After the fix, the product release type is displayed regardless of the number of versions.

2024-04-22 21:18 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20240419_amplify.md
> +* **Provider cannot provide the custom release version** - When using the product wizard to create a product, the option to set a custom version is now available when you decide to activate the produ
**Custom product version**

2024-04-23 18:01 UTC, georgiana-caras approved these changes

2024-04-23 20:09 UTC, robertengaxway approved these changes
I approve

2024-04-23 20:35 UTC, robertengaxway approved these changes
I approve

2024-04-23 22:11 UTC, merged