May 3 Release Notes
Axway/amplify-central pull request #446
Opened 2024-04-30 22:21 UTC by lbadenhop

Thank you for your contribution to the Amplify-Central repo.

## Describe the changes

Enter a brief description of your changes to communicate to the reviewers what you changed and why.

## Deploy preview link

Please add the deploy preview link to the **specific page** that you've changed.

## Checklist for contributors

Before submitting this PR:

* Verify that all status checks have passed
* For more information on the Markdown linter rules, see [DavidAnson/markdownlint](https://github.com/DavidAnson/markdownlint)
* For first-time contributors, ensure that you have signed the [Axway CLA](https://cla.axway.com/)

2024-04-30 22:22 UTC, docsbuilder commented
### <span aria-hidden="true">✅</span> Deploy preview is ready!

 |  Name | Link |
 |---------------------------------|------------------------|
 |<span aria-hidden="true">🔨</span> Latest commit | 53b6a56 |
 |<span aria-hidden="true">😎</span> Deploy preview | http://PR-446.amplify-central.opendocs-builder.pcloud.axway.int |

2024-05-06 22:11 UTC, cbordier approved these changes
I approve the changes

2024-05-09 06:15 UTC, georgiana-caras requested changes

2024-05-09 06:15 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20240503_amplify.md
> +* **Metrics Processing** - A fix was maded to allow the setting of an Apigee environment in which the Embedded Agent will discover Proxies from and gather Metrics on.
what was the defect that we tried to fix?

2024-05-09 06:15 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20240503_amplify.md
> +* **Duplicate plan** - It is now possible to create a product plan from an existing one regardless the plan status. When using this action it will not carry over all corrupted resources from the init
**Duplicate plan** - You can now create a new plan by duplicating an existing one. Any corrupted resources will not be included in the duplicate copy. Refer to (/docs/manage_product_foundry/manage_product_plans#duplicate-a-product-plan) for more details.

2024-05-09 06:15 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20240503_amplify.md
> +* **Migrating API Manager applications to Amplify Enterprise Marketplace applications** - A script is available to migrate the existing API Manager a into Marketplace applications so that consumer wi
A script is now available to migrate the existing API Manager into the Amplify Enterprise Marketplace. This will allow consumers to use their existing applications and credentials as they transition to use the experience enabled by the Marketplace.

2024-05-09 14:19 UTC, robertengaxway commented on content/en/docs/amplify_relnotes/20240503_amplify.md
> +* **Offline Usage Rerorts** - A fix was made for generating local platform usage reports when the traceability agent is not connected to the Axway API Manager or API Management Gateway.
typo looks fixed

2024-05-09 14:22 UTC, robertengaxway commented on content/en/docs/amplify_relnotes/20240503_amplify.md
> +* **Tracebility Agents** - A fix was made to support implementations that do not set the API revision value in tranactions events.  This would cause transactions to not be displayed on the API Health
typo looks fixed

2024-05-09 14:22 UTC, robertengaxway commented on content/en/docs/amplify_relnotes/20240503_amplify.md
> +* **OAuth Credential Updates** - A fix was made to support the update of OAuth credentials when a scope change is detected to an API Proxy.
Update the wording to indicate the credential request is updated

2024-05-09 14:25 UTC, robertengaxway commented on content/en/docs/amplify_relnotes/20240503_amplify.md
> +* **SOAP API subscriptions** - The Disovery Agent has been enhanced to provision/de-provision credentials for Enterprise Marektplace subscriptions.
updated

2024-05-09 14:26 UTC, robertengaxway commented on content/en/docs/amplify_relnotes/20240503_amplify.md
> +* **OAuth Credential Updates** - A fix was made to update the OAuth credentisls whenever a scope change is detected to an API Proxy.
updated

2024-05-09 14:27 UTC, robertengaxway commented on content/en/docs/amplify_relnotes/20240503_amplify.md
> +* **Provisioning/Deprovisioning of Marketplace subscriptions** - A fix was made to support the multiple versions of the Mulesoft Anypoint API.  The data from the Anypoint API is parsed so that Market
The Mulesoft Anypoint API had changed which we depend upon.  So we have to accomodate old and new Mulesoft API versions

2024-05-09 14:29 UTC, robertengaxway commented on content/en/docs/amplify_relnotes/20240503_amplify.md
> +The Graylog API Security agent has been released and update with the Axway Agent SDK. This agent will assess your runtime compliance of Unmanaged APIs from a security threat perspective by integratin
updated

2024-05-09 14:31 UTC, robertengaxway commented on content/en/docs/amplify_relnotes/20240503_amplify.md
> +* **Metrics Processing** - A fix was maded to allow the setting of an Apigee environment in which the Embedded Agent will discover Proxies from and gather Metrics on.
you can now set which one of multiple Apigee environments to collect metrics from.  Before it was only the first one.

2024-05-09 16:50 UTC, georgiana-caras approved these changes

2024-05-09 19:44 UTC, merged