May 17 Release Notes
Axway/amplify-central pull request #457
Opened 2024-05-16 18:35 UTC by lbadenhop

Thank you for your contribution to the Amplify-Central repo.

## Describe the changes

Enter a brief description of your changes to communicate to the reviewers what you changed and why.

## Deploy preview link

Please add the deploy preview link to the **specific page** that you've changed.

## Checklist for contributors

Before submitting this PR:

* Verify that all status checks have passed
* For more information on the Markdown linter rules, see [DavidAnson/markdownlint](https://github.com/DavidAnson/markdownlint)
* For first-time contributors, ensure that you have signed the [Axway CLA](https://cla.axway.com/)

2024-05-16 18:38 UTC, docsbuilder commented
### <span aria-hidden="true">✅</span> Deploy preview is ready!

 |  Name | Link |
 |---------------------------------|------------------------|
 |<span aria-hidden="true">🔨</span> Latest commit | 74f5b19 |
 |<span aria-hidden="true">😎</span> Deploy preview | http://PR-457.amplify-central.opendocs-builder.pcloud.axway.int |

2024-05-20 22:00 UTC, georgiana-caras requested changes

2024-05-20 22:45 UTC, robertengaxway commented on content/en/docs/amplify_relnotes/20240517_amplify.md
> +There are no new enhancements in this release.
fixed

2024-05-20 22:46 UTC, robertengaxway commented on content/en/docs/amplify_relnotes/20240517_amplify.md
> +* **Usage Audit Log** - A new Usage Audit log has been enabled by default.  This Usage log will store a usage count line each time it has been successfully communicated to the Axway Platform.  The us
fixed

2024-05-20 22:47 UTC, robertengaxway commented on content/en/docs/amplify_relnotes/20240517_amplify.md
> +| 01567300 <br />01578477   | APIGOV-27915 <br />APIGOV-27886 | **Issue**: The Discovery and Traceability Agent were restarting with a concurrent map read and map error <br />**Resolution**: A fix wa
fixed

2024-05-20 22:48 UTC, robertengaxway commented on content/en/docs/amplify_relnotes/20240517_amplify.md
> +|             | APIGOV-27892 | **Issue**: Azure API Service names were not being sanitized when stored in the API Server <br />**Resolution**: A fix was made so the API Service revision names which h
fixed

2024-05-20 22:49 UTC, robertengaxway commented on content/en/docs/amplify_relnotes/20240517_amplify.md
> +| 01544107 <br />01537104    | APIGOV-26808 | **Issue**: Cannot achive an Asset Release <br />**Resolution**: The was fixed as part of the Unable to add an asset to a oroduct issue  |
fixed

2024-05-20 23:55 UTC, merged