Replace charts.axway.com with repository.axway.com
Axway/amplify-central pull request #465
Opened 2024-06-10 21:00 UTC by lbadenhop

Thank you for your contribution to the Amplify-Central repo.

## Describe the changes

Due to security risks, change https://charts.axway.com to https://repository.axway.com

## Deploy preview link

Please add the deploy preview link to the **specific page** that you've changed.

## Checklist for contributors

Before submitting this PR:

* Verify that all status checks have passed
* For more information on the Markdown linter rules, see [DavidAnson/markdownlint](https://github.com/DavidAnson/markdownlint)
* For first-time contributors, ensure that you have signed the [Axway CLA](https://cla.axway.com/)

2024-06-10 21:01 UTC, docsbuilder commented
### <span aria-hidden="true">✅</span> Deploy preview is ready!

 |  Name | Link |
 |---------------------------------|------------------------|
 |<span aria-hidden="true">🔨</span> Latest commit | d1d9602 |
 |<span aria-hidden="true">😎</span> Deploy preview | http://PR-465.amplify-central.opendocs-builder.pcloud.axway.int |

2024-06-12 13:52 UTC, jcollins-axway requested changes

2024-06-13 17:53 UTC, jcollins-axway commented on content/en/docs/connect_manage_environ/connect_api_manager/deploy-your-agents-with-amplify-cli.md
> +helm repo pull <agent_filename>
get rid of this line

2024-06-13 17:57 UTC, jcollins-axway approved these changes

2024-06-13 17:58 UTC, robertengaxway commented on content/en/docs/connect_manage_environ/connect_api_manager/deploy-your-agents-with-amplify-cli.md
> +helm repo pull <agent_filename>
removed

2024-06-13 17:58 UTC, robertengaxway commented on content/en/docs/connect_manage_environ/connect_api_manager/deploy-your-agents-with-amplify-cli.md
>  helm upgrade --install --namespace <YOUR_NAMESPACE> v7-discovery axway/v7-discovery -f da-overrides.yaml
fixed all the names and urls

2024-06-13 17:59 UTC, robertengaxway approved these changes
reviewed with Jason

2024-06-13 18:04 UTC, merged