June 14 Release Notes
Axway/amplify-central pull request #466
Opened 2024-06-12 17:58 UTC by lbadenhop

Thank you for your contribution to the Amplify-Central repo.

## Describe the changes

Enter a brief description of your changes to communicate to the reviewers what you changed and why.

## Deploy preview link

Please add the deploy preview link to the **specific page** that you've changed.

## Checklist for contributors

Before submitting this PR:

* Verify that all status checks have passed
* For more information on the Markdown linter rules, see [DavidAnson/markdownlint](https://github.com/DavidAnson/markdownlint)
* For first-time contributors, ensure that you have signed the [Axway CLA](https://cla.axway.com/)

2024-06-12 18:00 UTC, docsbuilder commented
### <span aria-hidden="true">✅</span> Deploy preview is ready!

 |  Name | Link |
 |---------------------------------|------------------------|
 |<span aria-hidden="true">🔨</span> Latest commit | 5d6956b |
 |<span aria-hidden="true">😎</span> Deploy preview | http://PR-466.amplify-central.opendocs-builder.pcloud.axway.int |

2024-06-18 13:34 UTC, jcollins-axway commented on content/en/docs/amplify_relnotes/20240614_amplify.md
> +* **Dynamic Client Registration settings** - An enhancement has been made to enable the configuration of additional Dynamic Client Regstration protocol settings (e.g. to support Oracle Access Maanger
I realize these changes are in the SDK, but does it make sense to list it here and under v7?

2024-06-18 13:35 UTC, jcollins-axway commented on content/en/docs/amplify_relnotes/20240614_amplify.md
> +| 01570727    | APIGOV-28012 | **Issue**: In some deployment situations, the Traceability Agent could not be deployed with a Kubernetes StatefulSet. <br />**Resolution**: The StatefulSet deployment i
The issue is more "The Traceability Agent only supported deployment as a DaemonSet..."

2024-06-18 15:43 UTC, robertengaxway commented on content/en/docs/amplify_relnotes/20240614_amplify.md
> +| 01570727    | APIGOV-28012 | **Issue**: In some deployment situations, the Traceability Agent could not be deployed with a Kubernetes StatefulSet. <br />**Resolution**: The StatefulSet deployment i
Made edits after discussion with Jason

2024-06-18 15:48 UTC, robertengaxway commented on content/en/docs/amplify_relnotes/20240614_amplify.md
> +* **Dynamic Client Registration settings** - An enhancement has been made to enable the configuration of additional Dynamic Client Regstration protocol settings (e.g. to support Oracle Access Maanger
Removed the duplication from the V7 Agent section.   Added a line in the Agent SDK to indicate this is supported for V7 and Istio Agents only.

2024-06-18 15:52 UTC, robertengaxway approved these changes
I approve

2024-06-18 16:01 UTC, jcollins-axway approved these changes

2024-06-18 21:57 UTC, georgiana-caras requested changes

2024-06-18 21:57 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20240614_amplify.md
> +* **Mock Service support** - An enhancencement has been made to integrate a Mock service to simulate an API endpoint early in the API lifecycle based upon its API Specification. The Mocked endpoints
Through the embedded Mocking Service feature, providers now have the ability to create a mock endpoint early in theAPI lifecycle based upon its API Specification.

2024-06-18 21:58 UTC, georgiana-caras approved these changes

2024-06-18 21:59 UTC, robertengaxway commented on content/en/docs/amplify_relnotes/20240614_amplify.md
> +* **Mock Service support** - An enhancencement has been made to integrate a Mock service to simulate an API endpoint early in the API lifecycle based upon its API Specification. The Mocked endpoints
made that edit

2024-06-18 23:31 UTC, merged