APIGOV-28146 Add content for create/edit a mock endpoint
Axway/amplify-central pull request #467
Opened 2024-06-12 18:13 UTC by lbadenhop

Thank you for your contribution to the Amplify-Central repo.

## Describe the changes

Enter a brief description of your changes to communicate to the reviewers what you changed and why.

## Deploy preview link

Please add the deploy preview link to the **specific page** that you've changed.

## Checklist for contributors

Before submitting this PR:

* Verify that all status checks have passed
* For more information on the Markdown linter rules, see [DavidAnson/markdownlint](https://github.com/DavidAnson/markdownlint)
* For first-time contributors, ensure that you have signed the [Axway CLA](https://cla.axway.com/)

2024-06-13 22:36 UTC, georgiana-caras requested changes

2024-06-13 22:36 UTC, georgiana-caras commented on content/en/docs/manage_service_registry/service_management.md
> +A mock endpoint can be created, if the Service meets the [requirements](#create-mock-endpoint), by clicking the 3 ellipsis button and selecting **Create Mock Endpoint**.
I don't believe we need this paragraph here, under the list service page. There is already content in the "Create a mock endpoint" section about the places where you can create an enpoint.

2024-06-13 22:36 UTC, georgiana-caras commented on content/en/docs/connect_manage_environ/view_environments.md
> +        * Mock Endpoints: If [requirements](/docs/manage_service_registry/service_management/#create-mock-endpoint) are met a mock endpoint can be created from the **Services** tab. Simply click the
I would prefer to have a Note section here that describes the requirements.

2024-06-14 14:35 UTC, lbadenhop commented
@ColeSammonsAxway, can you please fix your linting errors https://apigw-builder.pcloud.axway.int/blue/organizations/jenkins/amplify-central-docs/detail/PR-467/9/pipeline/

2024-06-18 21:59 UTC, georgiana-caras approved these changes

2024-06-18 22:21 UTC, merged