APIGOV-28139 added audit log variables
Axway/amplify-central pull request #478
Opened 2024-06-28 07:21 UTC by alrosca

Thank you for your contribution to the Amplify-Central repo.

## Describe the changes

Enter a brief description of your changes to communicate to the reviewers what you changed and why.

## Deploy preview link

Please add the deploy preview link to the **specific page** that you've changed.

## Checklist for contributors

Before submitting this PR:

* Verify that all status checks have passed
* For more information on the Markdown linter rules, see [DavidAnson/markdownlint](https://github.com/DavidAnson/markdownlint)
* For first-time contributors, ensure that you have signed the [Axway CLA](https://cla.axway.com/)

2024-06-28 07:24 UTC, docsbuilder commented
### <span aria-hidden="true">✅</span> Deploy preview is ready!

 |  Name | Link |
 |---------------------------------|------------------------|
 |<span aria-hidden="true">🔨</span> Latest commit | 98cd7b4 |
 |<span aria-hidden="true">😎</span> Deploy preview | http://PR-478.amplify-central.opendocs-builder.pcloud.axway.int |

2024-06-28 12:25 UTC, jcollins-axway requested changes

2024-06-28 12:25 UTC, jcollins-axway commented on content/en/docs/connect_manage_environ/connect_api_manager/agent-variables.md
> +#### Audit log variables
This is the wrong place for these, since they are all common to all agents, they already here 
/docs/connect_manage_environ/connected_agent_common_reference/agent-variables and on the audit log doc here 
/docs/connect_manage_environ/connected_agent_common_reference/traceability_audit_logs

The transaction audit logs are missing, however, from /docs/connect_manage_environ/connected_agent_common_reference/agent-variables

2024-06-28 14:49 UTC, sbolosan approved these changes

2024-06-28 15:11 UTC, jcollins-axway approved these changes

2024-06-28 15:13 UTC, sbolosan approved these changes

2024-07-02 20:16 UTC, robertengaxway approved these changes
I approve

2024-07-03 16:01 UTC, lbadenhop approved these changes

2024-07-03 16:02 UTC, merged