July 12 Release Notes
Axway/amplify-central pull request #483
Opened 2024-07-10 19:51 UTC by lbadenhop

Thank you for your contribution to the Amplify-Central repo.

## Describe the changes

Enter a brief description of your changes to communicate to the reviewers what you changed and why.

## Deploy preview link

Please add the deploy preview link to the **specific page** that you've changed.

## Checklist for contributors

Before submitting this PR:

* Verify that all status checks have passed
* For more information on the Markdown linter rules, see [DavidAnson/markdownlint](https://github.com/DavidAnson/markdownlint)
* For first-time contributors, ensure that you have signed the [Axway CLA](https://cla.axway.com/)

2024-07-10 19:52 UTC, docsbuilder commented
### <span aria-hidden="true">✅</span> Deploy preview is ready!

 |  Name | Link |
 |---------------------------------|------------------------|
 |<span aria-hidden="true">🔨</span> Latest commit | 616f172 |
 |<span aria-hidden="true">😎</span> Deploy preview | http://PR-483.amplify-central.opendocs-builder.pcloud.axway.int |

2024-07-15 21:50 UTC, jcollins-axway commented on content/en/docs/amplify_relnotes/20240712_amplify.md
> +|             | APIGOV-28305 | **Issue**: An issue was found where the Kafka Discovery Agent would timeout with an error. <br />**Resolution**: A fix was made to the configuration of the Kafka Discov
This is kafka agent specific, not sdk

2024-07-15 21:51 UTC, jcollins-axway commented on content/en/docs/amplify_relnotes/20240712_amplify.md
> +|             | APIGOV-28305 | **Issue**: An issue was found where the Kafka Discovery Agent would timeout with an error. <br />**Resolution**: A fix was made to the configuration of the Kafka Discov
I think APIGOV-28034 is what is meant to be here

2024-07-16 16:23 UTC, robertengaxway commented on content/en/docs/amplify_relnotes/20240712_amplify.md
> +|             | APIGOV-28305 | **Issue**: An issue was found where the Kafka Discovery Agent would timeout with an error. <br />**Resolution**: A fix was made to the configuration of the Kafka Discov
made the edits

2024-07-16 16:24 UTC, robertengaxway approved these changes
approved

2024-07-16 21:38 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20240712_amplify.md
> +|             | APIGOV-28034 | **Issue**: An issue was found with the Traceability Agents where in some cases the event handling cause a consumer to not be correlated correctly to a transaction. <br
A fix was made to properly correlate the consumer with the transaction.

2024-07-16 21:40 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20240712_amplify.md
> +* **AWS Polling Mode support** - The on-premise AWS Agents only support AWS polling mode and a cost savings with the removal of the AWS Simple Queue Service.
have no idea what this AWS polling mode support is. Was it supposed to replace the AWS SQS which leads to cost savings?

2024-07-16 21:41 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20240712_amplify.md
> +| 01610765    | APIGOV-28290 | **Issue**: The display of the name (title) of API resources discovered by the SaaS embedded Azure agent was incorrect. <br />**Resolution**: The name (title) of API ser
The API Service name (title) is now accurately represented in Service Registry and Marketplace.

2024-07-16 21:48 UTC, robertengaxway commented on content/en/docs/amplify_relnotes/20240712_amplify.md
> +|             | APIGOV-28034 | **Issue**: An issue was found with the Traceability Agents where in some cases the event handling cause a consumer to not be correlated correctly to a transaction. <br
fixed

2024-07-16 21:50 UTC, robertengaxway commented on content/en/docs/amplify_relnotes/20240712_amplify.md
> +| 01610765    | APIGOV-28290 | **Issue**: The display of the name (title) of API resources discovered by the SaaS embedded Azure agent was incorrect. <br />**Resolution**: The name (title) of API ser
fixed

2024-07-16 22:01 UTC, georgiana-caras requested changes

2024-07-16 22:01 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20240712_amplify.md
> +| 01604288  | APIGOV-28233 | **Issue**: Access request screen is crashing. <br />**Resolution**: An error while reading the AssetRequestDefintion schema has been fixed to prevent the issue. |
An error has been fixed to prevent the issue.

2024-07-16 22:03 UTC, robertengaxway commented on content/en/docs/amplify_relnotes/20240712_amplify.md
> +* **AWS Polling Mode support** - The on-premise AWS Agents only support AWS polling mode and a cost savings with the removal of the AWS Simple Queue Service.
We now poll Cloudwatch, there is no need for SQS which is why its removed

2024-07-17 01:01 UTC, merged