July 26 Release Notes
Axway/amplify-central pull request #490
Opened 2024-07-25 18:05 UTC by lbadenhop

Thank you for your contribution to the Amplify-Central repo.

## Describe the changes

Enter a brief description of your changes to communicate to the reviewers what you changed and why.

## Deploy preview link

Please add the deploy preview link to the **specific page** that you've changed.

## Checklist for contributors

Before submitting this PR:

* Verify that all status checks have passed
* For more information on the Markdown linter rules, see [DavidAnson/markdownlint](https://github.com/DavidAnson/markdownlint)
* For first-time contributors, ensure that you have signed the [Axway CLA](https://cla.axway.com/)

2024-07-25 18:08 UTC, docsbuilder commented
### <span aria-hidden="true">✅</span> Deploy preview is ready!

 |  Name | Link |
 |---------------------------------|------------------------|
 |<span aria-hidden="true">🔨</span> Latest commit | c08105f |
 |<span aria-hidden="true">😎</span> Deploy preview | http://PR-490.amplify-central.opendocs-builder.pcloud.axway.int |

2024-07-29 16:55 UTC, jcollins-axway commented on content/en/docs/amplify_relnotes/20240726_amplify.md
> +* **Azure EventHub support** - The Agend SDK has support for the Azure EventHub configuration.
Neither of these make sense, I do not think referencing any specific dataplane will ever make sense for the SDK. The SDK may be enhanced for common functionality between dataplanes but never for a specific one.

These should be:

- "Enhanced support for External IdP configuration and usage" 
- "Async API spec generation"

2024-07-29 16:55 UTC, jcollins-axway commented on content/en/docs/amplify_relnotes/20240726_amplify.md
> +| 01617664    | APIGOV-28417 | **Issue**: A panic error can occur if the traceability agent (v1.1.84) is set offline mode. <br />**Resolution**: A fix was made to prevent a null pointer error when in
this is v7 not Azure

2024-07-29 17:01 UTC, jcollins-axway commented on content/en/docs/amplify_relnotes/20240726_amplify.md
> +| Apigee Edge                                | 0.1.44                   |
considering the message I referenced to you and Juan this morning, maybe we should add a note about the Google adjusting the Apigee Edge API as they decommission it?

2024-07-29 17:51 UTC, robertengaxway commented on content/en/docs/amplify_relnotes/20240726_amplify.md
> +* **Azure EventHub support** - The Agend SDK has support for the Azure EventHub configuration.
edits made

2024-07-29 17:59 UTC, robertengaxway commented on content/en/docs/amplify_relnotes/20240726_amplify.md
> +| 01617664    | APIGOV-28417 | **Issue**: A panic error can occur if the traceability agent (v1.1.84) is set offline mode. <br />**Resolution**: A fix was made to prevent a null pointer error when in
edits made

2024-07-29 18:08 UTC, robertengaxway commented on content/en/docs/amplify_relnotes/20240726_amplify.md
> +| Apigee Edge                                | 0.1.44                   |
I added an Apigee Edge limitation statement

2024-07-29 20:44 UTC, georgiana-caras requested changes

2024-07-29 20:44 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20240726_amplify.md
> +* **Enhanced Identity Provider support** - The Agent SDK has enhanced the support for external Identity Provider configuration and its usage.
@robertengaxway, can we say something along this line: The Agent SDK has been extended to add support for external Identity providers for Oauth.

2024-07-29 23:01 UTC, robertengaxway commented on content/en/docs/amplify_relnotes/20240726_amplify.md
> +* **Enhanced Identity Provider support** - The Agent SDK has enhanced the support for external Identity Provider configuration and its usage.
reworded to include "extended to add support .."

2024-07-30 19:55 UTC, merged