Subscription flow improvement
Axway/amplify-central pull request #501
Opened 2024-08-19 21:37 UTC by cbordier

Thank you for your contribution to the Amplify-Central repo.

## Describe the changes

Update the subscription flow
New screen for Application Registration
New screen for Credential list

## Deploy preview link

Please add the deploy preview link to the **specific page** that you've changed.

## Checklist for contributors

Before submitting this PR:

* Verify that all status checks have passed
* For more information on the Markdown linter rules, see [DavidAnson/markdownlint](https://github.com/DavidAnson/markdownlint)
* For first-time contributors, ensure that you have signed the [Axway CLA](https://cla.axway.com/)

2024-08-19 21:40 UTC, docsbuilder commented
### <span aria-hidden="true">✅</span> Deploy preview is ready!

 |  Name | Link |
 |---------------------------------|------------------------|
 |<span aria-hidden="true">🔨</span> Latest commit | ab0da93 |
 |<span aria-hidden="true">😎</span> Deploy preview | http://PR-501.amplify-central.opendocs-builder.pcloud.axway.int |

2024-08-23 22:11 UTC, cbordier commented
@lbadenhop can you start reviewing my english?

2024-08-28 23:37 UTC, georgiana-caras requested changes

2024-08-28 23:37 UTC, georgiana-caras commented on content/en/docs/integrate_with_central/customize_ard_crd.md
> +To customize the Application Registration screen, you need an `AccessRequestDefinition`. This object will contain the screen definition of the information required to provision access to a service an
you must duplicate the AccessRequestDefinition for each individual environment.

2024-08-28 23:37 UTC, georgiana-caras commented on content/en/docs/integrate_with_central/customize_ard_crd.md
> +If the APIService instance is already linked to an asset prior to adding the Application Registration definition, you must create a new release of the asset and a new release of the product to take t
If the APIService instance is already linked to an asset prior to adding the AccessRequestDefinition object

2024-08-30 18:28 UTC, georgiana-caras approved these changes

2024-08-30 18:54 UTC, merged