October 18 Release Notes
Axway/amplify-central pull request #547
Opened 2024-10-17 03:01 UTC by lbadenhop

Thank you for your contribution to the Amplify-Central repo.

## Describe the changes

Enter a brief description of your changes to communicate to the reviewers what you changed and why.

## Deploy preview link

Please add the deploy preview link to the **specific page** that you've changed.

## Checklist for contributors

Before submitting this PR:

* Verify that all status checks have passed
* For more information on the Markdown linter rules, see [DavidAnson/markdownlint](https://github.com/DavidAnson/markdownlint)
* For first-time contributors, ensure that you have signed the [Axway CLA](https://cla.axway.com/)

2024-10-17 03:03 UTC, docsbuilder commented
### <span aria-hidden="true">✅</span> Deploy preview is ready!

 |  Name | Link |
 |---------------------------------|------------------------|
 |<span aria-hidden="true">🔨</span> Latest commit | 3ccf541 |
 |<span aria-hidden="true">😎</span> Deploy preview | http://PR-547.amplify-central.opendocs-builder.pcloud.axway.int |

2024-10-18 21:31 UTC, vivekschauhan commented on content/en/docs/amplify_relnotes/20241018_amplify.md
> +[Connect Traceable](https://content/en/docs/content/en/docs/runtime_security/configure_runtime_compliance_traceable.md)
"https://content/en/docs" should be replaced with "/docs" for these links

2024-10-18 21:48 UTC, robertengaxway commented on content/en/docs/amplify_relnotes/20241018_amplify.md
> +[Connect Traceable](https://content/en/docs/content/en/docs/runtime_security/configure_runtime_compliance_traceable.md)
updated

2024-10-18 21:49 UTC, vivekschauhan approved these changes

2024-10-21 19:01 UTC, georgiana-caras requested changes

2024-10-21 19:01 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/20241018_amplify.md
> +* **REason of Subscription cancellation** - The reason of subscription cancellation is now displayed in the subscription details so that consumer are aware why their subscription have been terminated
**Display of Subscription Cancellation reason** – The reason for a subscription cancellation is now shown in the subscription details, so users know why their subscription ended. There are two possible reasons for cancellation: the subscription has reached its end date, or the provider has automatically canceled it due to unpaid invoices.

2024-10-21 21:53 UTC, robertengaxway commented on content/en/docs/amplify_relnotes/20241018_amplify.md
> +For customers which are unaware of new agent versions which have been released or have outdated agents, the **Agent Management** screen has been released within Topology.
edit made

2024-10-21 22:00 UTC, robertengaxway commented on content/en/docs/amplify_relnotes/20241018_amplify.md
> +* **Azure Filter Settings** - The Azure SaaS agent has the ability to use a filter setting string.  This option can be used to only discover APIs which match the filter settings for an Azure SaaS age
added link to variables and examples.  @lbadenhop check the directory link please

2024-10-22 01:05 UTC, merged