November Release Notes
Axway/amplify-central pull request #552
Opened 2024-10-28 20:27 UTC by lbadenhop

Thank you for your contribution to the Amplify-Central repo.

## Describe the changes

Enter a brief description of your changes to communicate to the reviewers what you changed and why.

## Deploy preview link

Please add the deploy preview link to the **specific page** that you've changed.

## Checklist for contributors

Before submitting this PR:

* Verify that all status checks have passed
* For more information on the Markdown linter rules, see [DavidAnson/markdownlint](https://github.com/DavidAnson/markdownlint)
* For first-time contributors, ensure that you have signed the [Axway CLA](https://cla.axway.com/)

2024-10-28 20:28 UTC, docsbuilder commented
### <span aria-hidden="true">✅</span> Deploy preview is ready!

 |  Name | Link |
 |---------------------------------|------------------------|
 |<span aria-hidden="true">🔨</span> Latest commit | ea5799d |
 |<span aria-hidden="true">😎</span> Deploy preview | http://PR-552.amplify-central.opendocs-builder.pcloud.axway.int |

2024-11-01 23:28 UTC, georgiana-caras requested changes

2024-11-01 23:28 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/2024nov_amplify.md
> +* **UI for Service Regostry**
**Jump to a specific page in Service Registry**

ENHANCEMENT<br />
Users can now **jump directly to a specific page** in the Service Registry, using the pagination control that is placed at the buttom of the table. Simply click on the "..." in the pagination controls to quickly access the page selector popup, where you can select the page you want to navigate to. This removes the need to having to click through multiple pages, saving time when browsing large lists of services.

2024-11-01 23:28 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/2024nov_amplify.md
> +* **Custom unit quota**
**Custom consumption units for billing and usage tracking**

PROVIDER BILLING; NEW FEATURE<br />
We are thrilled to introduce a powerful new feature that gives users the flexibility to define custom consumption units for more accurate and adaptable usage-based charging. This enhancement is designed to meet the evolving needs of service providers, particularly with the rise of generative AI and Large Language Model (LLM) services.
 * **Custom Consumption Unit**: Users can now define custom units for measuring and charging API usage. Previously, usage metrics were limited to charging by transactions only. This feature is especially valuable for providers offering generative AI services, where usage metrics like tokens are more appropriate.
 * **Use custom unit in plan quota**: Custom consumption units can now be used in the **product plan quota** definitions.

Refer to [Manage consumption unit](/docs/manage_product_foundry/manage_consumption_units) for more details.

2024-11-01 23:28 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/2024nov_amplify.md
> +* **Async API 3.0.0 support**
**Async API 3.0.0 support**

CONSUMER EXPERIENCE, ENHANCEMENT<br />
The component responsible for rendering API specifications has been upgraded to support **AsyncAPI v3.0.0**.
Users can now enjoy a visually appealing and well-structured presentation of AsyncAPI specifications directly in the Marketplace. In addition, when importing an AsyncAPI 3.0.0 specification into the **Service Registry**, the system will now automatically validate the definition. This ensures that only properly defined and compliant specifications are registered.

2024-11-01 23:28 UTC, georgiana-caras commented on content/en/docs/amplify_relnotes/2024nov_amplify.md
> +* **Enhancement title**
@cbordier , probably we need to remove this section before we publish. This is just part of the template.

2024-11-04 15:16 UTC, jcollins-axway commented on content/en/docs/amplify_relnotes/2024nov_amplify.md
> +| 01647785<br /> 01650304 | APIGOV-29069 | **Issue**: Axway API Management agent did not reflect the transision from "unhealthy" to a "running" states on the Ui. <br />**Resolution**: A fix was made
*transition*...*state*...*UI*

"...made to *represent* the agent state..."

2024-11-04 15:18 UTC, jcollins-axway commented on content/en/docs/amplify_relnotes/2024nov_amplify.md
> +| 01640474    | APIGOV-29157 | **Issue**: Axway API Management agent did not report metrics for a specific API. <br />**Resolution**: A fix was made to the handling of application name to check that
"...for a specific API when that API name is duplicated amongst services."

2024-11-04 15:18 UTC, jcollins-axway commented on content/en/docs/amplify_relnotes/2024nov_amplify.md
> +|             | APIGOV-29142 | **Issue**: Axway API Management Discovery agent would not be able to get the information needed to publish a proxy. <br />**Resolution**: A fix was made add retry logic
"A fix was made *to* add retry..."

2024-11-04 15:20 UTC, jcollins-axway commented on content/en/docs/amplify_relnotes/_index.md
> +| Axway API Management 7.6.2 SPx and 7.7 SPx | DA=v1.2.9 / TA=v1.2.7    | DA=v1.1.80 / TA=v1.1.81          |
Are we using a semantic version with or with out a "v" prefix? It is very mixed here. Should either be vX.Y.Z or just X.Y.Z, not mixed.

2024-11-04 15:21 UTC, jcollins-axway commented on content/en/docs/amplify_relnotes/_index.md
>  | Axway API Management 7.6.2 SPx and 7.7 SPx | DA=v1.2.7 / TA=v1.2.6    | DA=v1.1.80 / TA=v1.1.81          |
Why is this version not updated?

2024-11-04 17:32 UTC, robertengaxway commented on content/en/docs/amplify_relnotes/2024nov_amplify.md
> +| 01647785<br /> 01650304 | APIGOV-29069 | **Issue**: Axway API Management agent did not reflect the transision from "unhealthy" to a "running" states on the Ui. <br />**Resolution**: A fix was made
edited

2024-11-04 17:35 UTC, robertengaxway commented on content/en/docs/amplify_relnotes/2024nov_amplify.md
> +|             | APIGOV-29142 | **Issue**: Axway API Management Discovery agent would not be able to get the information needed to publish a proxy. <br />**Resolution**: A fix was made add retry logic
edited

2024-11-04 17:40 UTC, robertengaxway commented on content/en/docs/amplify_relnotes/_index.md
> +| Axway API Management 7.6.2 SPx and 7.7 SPx | DA=v1.2.9 / TA=v1.2.7    | DA=v1.1.80 / TA=v1.1.81          |
i removed the V

2024-11-04 17:41 UTC, robertengaxway commented on content/en/docs/amplify_relnotes/_index.md
>  | Axway API Management 7.6.2 SPx and 7.7 SPx | DA=v1.2.7 / TA=v1.2.6    | DA=v1.1.80 / TA=v1.1.81          |
Look at the heading , those are the correct version numbers for "October 18 Supported Agents"

2024-11-05 14:45 UTC, merged