APIGOV-29253 - add documentation for custom unit services
Axway/amplify-central pull request #567
Opened 2024-11-20 18:06 UTC by jcollins-axway

## Describe the changes

Add a new document with a sample of how to implement a custom unit metric service for the agents.

## Deploy preview link

## Checklist for contributors

Before submitting this PR:

* Verify that all status checks have passed
* For more information on the Markdown linter rules, see [DavidAnson/markdownlint](https://github.com/DavidAnson/markdownlint)
* For first-time contributors, ensure that you have signed the [Axway CLA](https://cla.axway.com/)

2024-11-20 18:08 UTC, docsbuilder commented
### <span aria-hidden="true">✅</span> Deploy preview is ready!

 |  Name | Link |
 |---------------------------------|------------------------|
 |<span aria-hidden="true">🔨</span> Latest commit | dffc04d |
 |<span aria-hidden="true">😎</span> Deploy preview | http://PR-567.amplify-central.opendocs-builder.pcloud.axway.int |

2024-11-20 18:15 UTC, jcollins-axway commented
@vivekschauhan @kasuvy @sbolosan @alrosca @dgghinea - please have a look over

2024-11-20 18:26 UTC, sbolosan commented on content/en/docs/connect_manage_environ/connected_agent_common_reference/agent-variables.md
> +For more information about the following variables see [Custom Units with Discovery and Traceability Agents](/docs/connect_manage_environ/connected_agent_common_reference/custom-unit-metrics).
change to, "For more information about the following variables see [Custom Unit Metric with Discovery and Traceability Agents...", since that's the page name?

2024-11-20 18:28 UTC, sbolosan commented on content/en/docs/connect_manage_environ/connected_agent_common_reference/custom-unit-metrics.md
> +Marketplace has the ability to create and track usage of custom units. These custom units may also be used in a Product Plan Quota. To enable the tracking of the usage and associating it to a proper
(add comma) "associating it to a proper quota, the Discovery

2024-11-20 20:02 UTC, sbolosan commented on content/en/docs/connect_manage_environ/connected_agent_common_reference/custom-unit-metrics.md
> +The RPC will be called for each and every access request event the Discovery Agent receives, if the metric service doe snot need to handle the event it may simply reply with an empty response. If the
doe snot = does not

then (add comma) 
"does not need to handle the event, "

2024-11-20 20:02 UTC, sbolosan commented on content/en/docs/connect_manage_environ/connected_agent_common_reference/custom-unit-metrics.md
> +The RPC will be called for each and every access request event the Discovery Agent receives, if the metric service doe snot need to handle the event it may simply reply with an empty response. If the
(add comma) If the metric service does need to handle the request, it can

2024-11-20 20:03 UTC, sbolosan commented on content/en/docs/connect_manage_environ/connected_agent_common_reference/custom-unit-metrics.md
> +The RPC will be called for each and every access request event the Discovery Agent receives, if the metric service doe snot need to handle the event it may simply reply with an empty response. If the
change "if their was a failure" to "if there was a failure"

2024-11-20 20:05 UTC, sbolosan commented on content/en/docs/connect_manage_environ/connected_agent_common_reference/custom-unit-metrics.md
> +In the sample below the metric service receives the quotaInfo message. If within that info custom unit and quota data is provided the service will handle it as needed. In all cases the service stores
(add comma) - In the sample below, the metric service...

break it up better?
If within the quotaInfo message, quota data is provided, the service will handle it as needed.

Not sure ^^^ what. you're trying to say.

2024-11-20 20:07 UTC, sbolosan commented on content/en/docs/connect_manage_environ/connected_agent_common_reference/custom-unit-metrics.md
> +In the sample below the metric service receives the quotaInfo message. If within that info custom unit and quota data is provided the service will handle it as needed. In all cases the service stores
(add comma) In all cases, the service stores the Application... 

... "API IDs, for the ones which relate to the gateway... "

2024-11-20 20:10 UTC, sbolosan commented on content/en/docs/connect_manage_environ/connected_agent_common_reference/custom-unit-metrics.md
> +Since this service will be used by both the Discovery and Traceability agents. Below are the environment variables that can be added to the agents, given the metric service is on the same machine as
Since this service will be used by both the Discovery and Traceability agents, the environment variables below can be added to the agent's configuration.  One prerequisite is that the metric service is on the same machine and also listening on port 50011.

2024-11-20 20:26 UTC, sbolosan commented on content/en/docs/connect_manage_environ/connected_agent_common_reference/custom-unit-metrics.md
> +The RPC will be called for each and every access request event the Discovery Agent receives. Uf the metric service does not need to handle the event, it may simply reply with an empty response. If th
Uf -> If

2024-11-20 20:43 UTC, jcollins-axway commented on content/en/docs/connect_manage_environ/connected_agent_common_reference/agent-variables.md
> +
yes, thank you

2024-11-20 20:44 UTC, sbolosan approved these changes

2024-11-20 20:50 UTC, sbolosan commented on content/en/docs/connect_manage_environ/connected_agent_common_reference/agent-variables.md
> +| AGENTFEATURES_METRICSERVICES_REJECTONFAIL | If set to true any error with the quota enforcement will fail the provisioning event in Marketplace |
(add comma) If set to true, any error with the quota...

2024-11-22 09:19 UTC, vivekschauhan approved these changes

2024-12-12 22:17 UTC, robertengaxway approved these changes
I approve

2024-12-12 22:34 UTC, cbordier approved these changes
I approve

2024-12-12 23:09 UTC, georgiana-caras requested changes
Please update content with the changes requested.

2024-12-12 23:09 UTC, georgiana-caras commented on content/en/docs/connect_manage_environ/connected_agent_common_reference/custom-unit-metrics.md
> +The MetricReporting service is used by Traceability Agents. Upon startup the agent will connect to each configured service. The connection opened will be a persistent stream connection in which the s
The **MetricReporting** service is used by **Traceability Agents** to send custom metric usage reports.

**Key Points**

* Upon startup, the Traceability Agent establishes a persistent connection to each connected service.
* Metric usage reports are sent via this connection as needed.
* The agent caches received reports and includes them in its periodic metric reporting cycle.
* If the connection is lost, the agent retries until the connection is restored.

2024-12-12 23:09 UTC, georgiana-caras commented on content/en/docs/connect_manage_environ/connected_agent_common_reference/custom-unit-metrics.md
> +
**Example: Report metrics events**

2024-12-12 23:09 UTC, georgiana-caras commented on content/en/docs/connect_manage_environ/connected_agent_common_reference/custom-unit-metrics.md
> +## Setup the agent configuration
## Step 2: Setup the agent configuration

2024-12-12 23:09 UTC, georgiana-caras commented on content/en/docs/connect_manage_environ/connected_agent_common_reference/custom-unit-metrics.md
> +Since this service will be used by both the Discovery and Traceability agents the environment variables below can be added to the agents configuration. In this example the metric service is on the sa
Both Discovery and Traceability agents require configuration to connect to the custom metric service.
**Configuration Example**
Assume the metric service is hosted on the same machine as the agents `(localhost)` and listens on port `50011.` Add the following environment variables to the agent's configuration:
```shell
# Enable the metric service
AGENTFEATURES_METRICSERVICES_ENABLE_1=true  

# Define the service URL
AGENTFEATURES_METRICSERVICES_URL_1=localhost:50011
```
The configuration variables may be replicated for as many services as needed, incrementing the index( e.g, _1, _2).

## Summary
You have now:
* Created a custom unit metric service to manage quotas and track usage.
* Configured Discovery and Traceability agents to connect to the service.
With these steps completed, your agents can enforce quotas for custom units and report usage effectively.

2024-12-12 23:43 UTC, georgiana-caras requested changes

2024-12-12 23:43 UTC, georgiana-caras commented on content/en/docs/manage_product_foundry/manage_consumption_units.md
> +MAnage the consumption units you want to monetize.
Wrong formatting in MAnage
Manage the consumption units you want to monetize.

2024-12-12 23:43 UTC, georgiana-caras commented on content/en/docs/manage_product_foundry/manage_consumption_units.md
> +A consumption unit defines the billable units. For example: Transactions, Seats, Messages. Used with the quotas to describe the pricing and how many units a consumer is entitled to use.
A **consumption unit** represents the billable unit of measurement used to define and track how resources or services are consumed. It is a fundamental concept for managing quotas and determining pricing in usage-based systems. Common consumption units include **Transactions, Seats, Messages**, or any custom unit defined for specific business needs.

Consumption units are used to:

* Define how many units a consumer is entitled to use (quotas).
* Establish the basis for billing consumers based on their usage.

2024-12-12 23:43 UTC, georgiana-caras commented on content/en/docs/manage_product_foundry/manage_consumption_units.md
> +By default the product comes with the **Transaction** consumption unit. This allow to bill consumer based on the number of request they are executing.
By default, the product includes the **Transaction** consumption unit. This allows billing to be based on the number of requests the clients execute.

2024-12-12 23:43 UTC, georgiana-caras commented on content/en/docs/manage_product_foundry/manage_consumption_units.md
> +1. Navigate to *Catalog > Product Foundry* > **Consumption Units**. This open the consumption unit page.
Navigate to **Catalog > Product Foundry > Consumption Units**.  This will open the **Consumption Units** page, where you can view a list of all available consumption units.

2024-12-12 23:43 UTC, georgiana-caras commented on content/en/docs/manage_product_foundry/manage_consumption_units.md
> +View the following information for all consumption units:
On the Consumption Units page, you can view the following information for each consumption unit:

* **Unit Name**: The display name of the consumption unit, shown to consumers in the plan quota definition.
* **Logical Name**: The technical identifier for the consumption unit.
* **Description**: A brief description explaining the purpose of the consumption unit.
* **Plans**: The number of product plans currently using this consumption unit.
* **Modified Date**: The date when the consumption unit was last updated.

2024-12-12 23:43 UTC, georgiana-caras commented on content/en/docs/manage_product_foundry/manage_consumption_units.md
> +The ellipsis menu allows to:
The ellipsis (⋮) menu next to each consumption unit offers additional management options:

1. **Edit**:
Allows you to update the details of a consumption unit. Refer to the [Edit a Consumption Unit](#edit-a-consumption-unit) section for detailed instructions.
2. **Translate**:
Enables you to translate the title and description of the consumption unit into multiple languages. For more information, see [Consumption Unit Multi-Language](#consumption-unit-multi-language).
3. **Delete**:
To [delete](#delete-a-consumption-unit) the consumption unit from the product.

2024-12-12 23:43 UTC, georgiana-caras commented on content/en/docs/manage_product_foundry/manage_consumption_units.md
> +To report custom unit, a service (Custom Unit Service) will have to be implemented in order to compute the information the Traceability Agent will send back to Amplify Platform.
To report a custom unit, you need to create a Custom Unit Service. This service will calculate the necessary information for the Traceability Agent to send back to the Amplify Platform.

2024-12-12 23:43 UTC, georgiana-caras commented on content/en/docs/manage_product_foundry/manage_consumption_units.md
> +Once a consumer request an access to an API via a Marketplace application, an event is generated. This event can be listen so that anyone can react on it. Typically our Discovery Agent listen to that
When a consumer requests access to an API via a Marketplace application, an event is generated. This event can be monitored so that systems can respond to it. For example, the Discovery Agent listens for this event to apply a quota on the Gateway when linking the application to the API.

When an API call is made, the Gateway logs the activity in **eventlog** or **openlog**. The Traceability Agent monitors these logs to generate transaction metrics and sends those metrics to the Amplify Platform.

For custom consumption units, the Custom Unit Service needs to:

1. **Monitor Quota Provisioning**:
   * Listen for quota provisioning events to track application and API link creation.
   * Optionally enforce quotas on the Gateway during this process.
2. **Calculate and Report Usage**:
   * Compute the number of custom units used for a specific API within the application.
   * Send this usage data to the Traceability Agent, which reports it to the Amplify Platform.
This process ensures that custom units are properly tracked and integrated with the Amplify Platform for reporting and enforcement.

2024-12-12 23:43 UTC, georgiana-caras commented on content/en/docs/manage_product_foundry/manage_consumption_units.md
> +Refer to [Use Custom Units with Discovery and Traceability Agents](/docs/connect_manage_environ/connected_agent_common_reference/custom-unit-metrics) for more information about its implementation.
Refer to [Reporting custom units usage](/docs/connect_manage_environ/connected_agent_common_reference/custom-unit-metrics) for more information about its implementation

2024-12-12 23:51 UTC, cbordier commented on content/en/docs/manage_product_foundry/manage_consumption_units.md
> +1. Navigate to *Catalog > Product Foundry* > **Consumption Units**. This open the consumption unit page.
@georgiana-caras we use to have italic for the menu navigation every where in the doc... Should we really change that?

2024-12-13 20:04 UTC, merged