Create page in Integrate with Amplify Central section “query-the-traceability-apis-with-lexus”
Axway/amplify-central pull request #66
Opened 2021-12-18 00:59 UTC by ingo

Automatically generated by Netlify CMS

2021-12-18 01:12 UTC, ingo commented
This is a complex topic, so it may need some additional review or commenting by a tech writer to make sure the description is clear.

2021-12-23 21:40 UTC, lbadenhop commented
@cbordier Need to discuss before merging.

2022-01-05 18:35 UTC, lbadenhop commented on content/en/docs/integrate_with_central/query-the-traceability-apis-with-lexus.md
> +## API authorization
```suggestion
## Prerequisite - API authorization
```

2022-01-05 18:36 UTC, lbadenhop commented on content/en/docs/integrate_with_central/query-the-traceability-apis-with-lexus.md
> +## Amplify Central
```suggestion
## Amplify Central use case
```

2022-01-05 18:38 UTC, lbadenhop commented on content/en/docs/integrate_with_central/query-the-traceability-apis-with-lexus.md
> +One common use case is to call the various APIs inside Amplify Central to retrieve summaries of transactions, events, or an individual transaction or event. See [https://docs.axway.com/category/api](
```suggestion
One common use case is to call the various APIs inside Amplify Central to retrieve summaries of transactions, events, or an individual transaction or event. See [https://docs.axway.com/category/api](https://docs.axway.com/category/api) > Amplify Platform > Traceability Connector API.

You can use whichever of the following methods you feel the most comfortable with to call the APIs. 
```

2022-01-05 18:40 UTC, lbadenhop commented on content/en/docs/integrate_with_central/query-the-traceability-apis-with-lexus.md
> +Alternatively, you can use cURL. An example of calling via cURL is shown below.
```suggestion
An example of calling APIs via cURL is shown below.
```

2022-01-05 18:43 UTC, lbadenhop commented on content/en/docs/integrate_with_central/query-the-traceability-apis-with-lexus.md
> +You may use whatever mechanism you feel most comfortable with to call the APIs. This script shows an example of exercising the API calls directly from the command line:
```suggestion
### Command line

This script shows an example of exercising the API calls directly from the command line:
```

2022-01-05 18:46 UTC, lbadenhop commented on content/en/docs/integrate_with_central/query-the-traceability-apis-with-lexus.md
> +## Transaction events
```suggestion
## Transaction event examples
```

2022-01-05 18:48 UTC, lbadenhop commented on content/en/docs/integrate_with_central/query-the-traceability-apis-with-lexus.md
> +Use the following data to query details out of the APIs.
```suggestion

```

2022-01-05 18:49 UTC, lbadenhop commented on content/en/docs/integrate_with_central/query-the-traceability-apis-with-lexus.md
> +Last 100 events, both summaries and events:
```suggestion
### Last 100 events, both summaries and events
```

2022-01-05 18:50 UTC, lbadenhop commented on content/en/docs/integrate_with_central/query-the-traceability-apis-with-lexus.md
> +Otherwise, you can show just transactionSummary or transactionEvent events:
```suggestion
### Show only transactionSummary or transactionEvent events
```

2022-01-05 18:51 UTC, lbadenhop commented on content/en/docs/integrate_with_central/query-the-traceability-apis-with-lexus.md
> +A transaction summary event looks like:
```suggestion
Transaction summary event
```

2022-01-05 18:52 UTC, lbadenhop commented on content/en/docs/integrate_with_central/query-the-traceability-apis-with-lexus.md
> +A transaction event looks like:
```suggestion
### Transaction event
```

2022-01-05 18:57 UTC, lbadenhop requested changes
@cbordier Please review my edits and suggestions for accuracy.

2022-01-05 19:36 UTC, ingo reviewed
Changes all look good to me. The CI workflow failed, so I assume there is a markdown linting error now introduced. Are you able to correct that, or would you like me to?

2022-01-05 19:39 UTC, lbadenhop commented
@ingo  I can correct the linting error. There is still one commit suggestion that isn't resolved. Can you take a look? Thanks!

2022-01-05 19:40 UTC, ingo commented
Okay, sorry, missed it. I think I got it now.

2022-01-05 19:46 UTC, lbadenhop approved these changes

2022-01-05 20:07 UTC, cbordier approved these changes
I approve the changes

2022-01-05 20:09 UTC, merged